const FLASHCARDS = [
  { id: 'd1-val', deal: 1, front: 'Microsoft–LinkedIn: deal value & premium', back: '$26.2bn all-cash · $196/share · 49.5% premium · closed Dec 2016' },
  { id: 'd1-fin', deal: 1, front: 'Microsoft–LinkedIn: how was it financed?', back: '~$20bn corporate bond issuance at ~2% — avoided repatriating >$100bn offshore cash (35% tax)' },
  { id: 'd1-bid', deal: 1, front: 'Microsoft vs Salesforce: why did LinkedIn pick Microsoft?', back: 'MS $196 all-cash vs SF $186 cash+stock — no exchange-ratio risk, no financing condition, certainty of close' },
  { id: 'd1-type', deal: 1, front: 'Microsoft–LinkedIn: deal type', back: 'Scope deal — professional data, cloud, CRM; not cost-cutting. Largest pure-software acquisition at announcement.' },
  { id: 'd1-post', deal: 1, front: 'Microsoft–LinkedIn: integration lesson', back: 'Federated autonomy — Weiner stayed CEO; opposite of Nokia failure. Azure migration $150M cost synergy by 2018.' },
  { id: 'd2-val', deal: 2, front: 'CaixaBank–Bankia: structure', back: 'All-share merger by absorption · 0.6845 CBK shares per Bankia share · 20% premium over unaffected ratio' },
  { id: 'd2-why', deal: 2, front: 'CaixaBank–Bankia: why merge in 2020?', back: 'Negative rates, branch overcapacity (−49% since 2008), COVID provisions (€26.5bn H1 2020), ECB supportive of consolidation' },
  { id: 'd2-scale', deal: 2, front: 'CaixaBank–Bankia: combined scale', back: 'Spain\'s largest domestic bank · >€660bn assets · >20M customers · ~€368bn loan book' },
  { id: 'd2-bankia', deal: 2, front: 'Bankia: formation & state role', back: '2010 from 7 cajas · nationalised 2012 (€22.4bn bailout) · FROB ~61.8% — state exit drove timing' },
  { id: 'd3-val', deal: 3, front: 'Amazon–Whole Foods: price', back: '$13.7bn all-cash · $42/share · ~27% premium · Jun 2017 announced, Aug 2017 closed' },
  { id: 'd3-why', deal: 3, front: 'Amazon–Whole Foods: strategic logic', back: 'Scope — 456 urban stores for fulfilment/pickup; <4% of Amazon revenue; bought infrastructure not earnings' },
  { id: 'd3-act', deal: 3, front: 'Whole Foods: pre-deal pressure', back: 'JANA activist 8.8% stake · 8 quarters comp-store declines · premium organic cost base vs mass-market' },
  { id: 'd4-val', deal: 4, front: 'Facebook–Instagram: consideration', back: '~$1bn announced (~$715m at close) · $300m cash + 23M FB shares · Apr 2012, 5 weeks before $16bn IPO' },
  { id: 'd4-why', deal: 4, front: 'Facebook–Instagram: why buy?', back: 'Mobile pivot · pre-empt Twitter (~$525m bid) · acqui-hire 13 people · zero revenue, 30M users' },
  { id: 'd4-post', deal: 4, front: 'Instagram post-acquisition', back: 'Deferred integration · 30M→3bn MAU · $32bn+ annual ad revenue by 2024 · among best M&A ever' },
  { id: 'd5-val', deal: 5, front: 'Kraft–Cadbury: deal facts', back: '$19.5bn · Feb 2010 close · hostile→friendly · ~50% premium to pre-bid price' },
  { id: 'd5-why', deal: 5, front: 'Kraft–Cadbury: why inevitable?', back: 'Mars–Wrigley $23bn (2008) left Cadbury as only large independent confectioner · India distribution key prize' },
  { id: 'd5-fail', deal: 5, front: 'Kraft–Cadbury: what failed?', back: 'Somerdale plant U-turn · revenue synergies missed · Mondelez spin 2012 · Kraft SH short-term negative' },
  { id: 'd5-4block', deal: 5, front: 'Kraft 4-block framework', back: 'Timing (post-GFC) · Efficiency ($675M synergies) · Market position (India/EM) · Managers/opportunity (Peltz + hubris)' },
  { id: 'd6-val', deal: 6, front: 'Disney–Fox: final price', back: '$71.3bn · closed Mar 2019 · cash+stock election ($38 cash or 0.4517 DIS shares)' },
  { id: 'd6-bid', deal: 6, front: 'Disney–Fox bidding war', back: 'Dec 2017 Disney $52.4bn stock → May 2018 Comcast $65bn cash → Jun 2018 Disney $71.3bn; Comcast withdrew' },
  { id: 'd6-why', deal: 6, front: 'Disney–Fox: what was acquired?', back: 'Studios, FX, Nat Geo, Star India, Hulu control — NOT Fox News/Broadcast (new Fox Corp)' },
  { id: 'd6-sector', deal: 6, front: 'Disney–Fox: sector driver', back: 'Netflix disruption (33M→167M subs) · IP scarcity · DTC non-negotiable · content arms race' },
  { id: 'd7-val', deal: 7, front: 'Marriott–Starwood: consideration', back: '0.80 MAR shares + $21 cash per HOT share (raised after Anbang bid) · closed Sep 2016' },
  { id: 'd7-why', deal: 7, front: 'Marriott–Starwood: core assets', back: 'SPG loyalty (50% of Starwood nights) · 5,700 hotels / 1.1M rooms · OTA bargaining power · $200–250M cost synergies' },
  { id: 'd7-anbang', deal: 7, front: 'Marriott–Starwood: Anbang', back: 'Chinese consortium counterbid Mar 2016 → forced Marriott to raise offer · Anbang later bought Strategic Hotels $6.5bn' },
  { id: 'd8-saga', deal: 8, front: 'VW–Porsche: the reversal', back: 'Porsche built 74.1% VW stake via options → €14bn debt + GFC → VW €700m rescue loan Mar 2009 → VW absorbed Porsche AG 2012' },
  { id: 'd8-family', deal: 8, front: 'VW–Porsche: family control', back: 'Porsche-Piëch family · Porsche SE holds 50.7% VW voting shares · "Kampf der Egos" Wolfgang vs Piëch' },
  { id: 'd8-roe', deal: 8, front: 'VW–Porsche: RoE asymmetry (~2005)', back: 'Porsche 22.8% vs VW 3.0% — explains options strategy and carrying value vs cash paid' },
  { id: 'd9-val', deal: 9, front: 'LVMH–Tiffany: price path', back: '$120 rejected → $135 signed Nov 2019 → litigation → $131.50 renegotiated Oct 2020 → closed Jan 2021 ($15.8bn total)' },
  { id: 'd9-why', deal: 9, front: 'LVMH–Tiffany: strategic logic', back: 'Strengthen Watches & Jewellery (8% of LVMH) · close Richemont/Cartier gap · US bridal · Asia via LVMH network' },
  { id: 'd9-mac', deal: 9, front: 'LVMH–Tiffany: pandemic dispute', back: 'LVMH tried to withdraw Sep 2020 · Tiffany sued · renegotiated $425M price cut · MAC clause litigation' },
  { id: 'x-scale', deal: 0, front: 'Scale deal vs scope deal', back: 'Scale = same business, cost synergies (banks, hotels) · Scope = new capabilities/markets (LinkedIn, Instagram, Whole Foods)' },
  { id: 'x-cash', deal: 0, front: 'When does all-cash win?', back: 'Target wants certainty · depressed stock · no exchange-ratio risk · bidder has liquidity/debt access (MS, Amazon, LVMH)' },
  { id: 'x-hostile', deal: 0, front: 'Hostile takeover example', back: 'Kraft–Cadbury: UK Takeover Panel · Somerdale controversy changed UK politics · eventual friendly acceptance' },
  { id: 'x-badwill', deal: 0, front: 'Badwill in banking', back: 'Buy below book value → negative goodwill · ECB: use profits to strengthen combined entity capital (CaixaBank–Bankia context)' },
];
