const FLASHCARDS = [
  { id: 'd1-val', deal: 1, front: 'Microsoft–LinkedIn: deal value & premium', back: '$26.2bn all-cash · $196/share · 49.5% premium · closed Dec 2016' },
  { id: 'd1-fin', deal: 1, front: 'Microsoft–LinkedIn: how was it financed?', back: '~$20bn corporate bond issuance at ~2%  -  avoided repatriating >$100bn offshore cash (35% tax)' },
  { id: 'd1-bid', deal: 1, front: 'Microsoft vs Salesforce: why did LinkedIn pick Microsoft?', back: 'MS $196 all-cash vs SF $186 cash+stock  -  no exchange-ratio risk, no financing condition, certainty of close' },
  { id: 'd1-type', deal: 1, front: 'Microsoft–LinkedIn: deal type', back: 'Scope deal  -  professional data, cloud, CRM; not cost-cutting. Largest pure-software acquisition at announcement.' },
  { id: 'd1-post', deal: 1, front: 'Microsoft–LinkedIn: integration lesson', back: 'Federated autonomy  -  Weiner stayed CEO; opposite of Nokia failure. Azure migration $150M cost synergy by 2018.' },
  { id: 'd2-val', deal: 2, front: 'CaixaBank–Bankia: structure', back: 'All-share merger by absorption · 0.6845 CBK shares per Bankia share · 20% premium over unaffected ratio' },
  { id: 'd2-why', deal: 2, front: 'CaixaBank–Bankia: why merge in 2020?', back: 'Negative rates, branch overcapacity (−49% since 2008), COVID provisions (€26.5bn H1 2020), ECB supportive of consolidation' },
  { id: 'd2-scale', deal: 2, front: 'CaixaBank–Bankia: combined scale', back: 'Spain\'s largest domestic bank · >€660bn assets · >20M customers · ~€368bn loan book' },
  { id: 'd2-bankia', deal: 2, front: 'Bankia: formation & state role', back: '2010 from 7 cajas · nationalised 2012 (€22.4bn bailout) · FROB ~61.8%  -  state exit drove timing' },
  { id: 'd3-val', deal: 3, front: 'Amazon–Whole Foods: price', back: '$13.7bn all-cash · $42/share · ~27% premium · Jun 2017 announced, Aug 2017 closed' },
  { id: 'd3-why', deal: 3, front: 'Amazon–Whole Foods: strategic logic', back: 'Scope  -  456 urban stores for fulfilment/pickup; <4% of Amazon revenue; bought infrastructure not earnings' },
  { id: 'd3-act', deal: 3, front: 'Whole Foods: pre-deal pressure', back: 'JANA activist 8.8% stake · 8 quarters comp-store declines · premium organic cost base vs mass-market' },
  { id: 'd4-val', deal: 4, front: 'Facebook–Instagram: consideration', back: '~$1bn announced (~$715m at close) · $300m cash + 23M FB shares · Apr 2012, 5 weeks before $16bn IPO' },
  { id: 'd4-why', deal: 4, front: 'Facebook–Instagram: why buy?', back: 'Mobile pivot · pre-empt Twitter (~$525m bid) · acqui-hire 13 people · zero revenue, 30M users' },
  { id: 'd4-post', deal: 4, front: 'Instagram post-acquisition', back: 'Deferred integration · 30M→3bn MAU · $32bn+ annual ad revenue by 2024 · among best M&A ever' },
  { id: 'd5-val', deal: 5, front: 'Kraft–Cadbury: deal facts', back: '$19.5bn · Feb 2010 close · hostile→friendly · ~50% premium to pre-bid price' },
  { id: 'd5-why', deal: 5, front: 'Kraft–Cadbury: why inevitable?', back: 'Mars–Wrigley $23bn (2008) left Cadbury as only large independent confectioner · India distribution key prize' },
  { id: 'd5-fail', deal: 5, front: 'Kraft–Cadbury: what failed?', back: 'Somerdale plant U-turn · revenue synergies missed · Mondelez spin 2012 · Kraft SH short-term negative' },
  { id: 'd5-4block', deal: 5, front: 'Kraft 4-block framework', back: 'Timing (post-GFC) · Efficiency ($675M synergies) · Market position (India/EM) · Managers/opportunity (Peltz + hubris)' },
  { id: 'd6-val', deal: 6, front: 'Disney–Fox: final price', back: '$71.3bn · closed Mar 2019 · cash+stock election ($38 cash or 0.4517 DIS shares)' },
  { id: 'd6-bid', deal: 6, front: 'Disney–Fox bidding war', back: 'Dec 2017 Disney $52.4bn stock → May 2018 Comcast $65bn cash → Jun 2018 Disney $71.3bn; Comcast withdrew' },
  { id: 'd6-why', deal: 6, front: 'Disney–Fox: what was acquired?', back: 'Studios, FX, Nat Geo, Star India, Hulu control  -  NOT Fox News/Broadcast (new Fox Corp)' },
  { id: 'd6-sector', deal: 6, front: 'Disney–Fox: sector driver', back: 'Netflix disruption (33M→167M subs) · IP scarcity · DTC non-negotiable · content arms race' },
  { id: 'd7-val', deal: 7, front: 'Marriott–Starwood: consideration', back: '0.80 MAR shares + $21 cash per HOT share (raised after Anbang bid) · closed Sep 2016' },
  { id: 'd7-why', deal: 7, front: 'Marriott–Starwood: core assets', back: 'SPG loyalty (50% of Starwood nights) · 5,700 hotels / 1.1M rooms · OTA bargaining power · $200–250M cost synergies' },
  { id: 'd7-anbang', deal: 7, front: 'Marriott–Starwood: Anbang', back: 'Chinese consortium counterbid Mar 2016 → forced Marriott to raise offer · Anbang later bought Strategic Hotels $6.5bn' },
  { id: 'd8-saga', deal: 8, front: 'VW–Porsche: the reversal', back: 'Porsche built 74.1% VW stake via options → €14bn debt + GFC → VW €700m rescue loan Mar 2009 → VW absorbed Porsche AG 2012' },
  { id: 'd8-family', deal: 8, front: 'VW–Porsche: family control', back: 'Porsche-Piëch family · Porsche SE holds 50.7% VW voting shares · "Kampf der Egos" Wolfgang vs Piëch' },
  { id: 'd8-roe', deal: 8, front: 'VW–Porsche: RoE asymmetry (~2005)', back: 'Porsche 22.8% vs VW 3.0%  -  explains options strategy and carrying value vs cash paid' },
  { id: 'd9-val', deal: 9, front: 'LVMH–Tiffany: price path', back: '$120 rejected → $135 signed Nov 2019 → litigation → $131.50 renegotiated Oct 2020 → closed Jan 2021 ($15.8bn total)' },
  { id: 'd9-why', deal: 9, front: 'LVMH–Tiffany: strategic logic', back: 'Strengthen Watches & Jewellery (8% of LVMH) · close Richemont/Cartier gap · US bridal · Asia via LVMH network' },
  { id: 'd9-mac', deal: 9, front: 'LVMH–Tiffany: pandemic dispute', back: 'LVMH tried to withdraw Sep 2020 · Tiffany sued · renegotiated $425M price cut · MAC clause litigation' },
  { id: 'x-scale', deal: 0, front: 'Scale deal vs scope deal', back: 'Scale = same business, cost synergies (banks, hotels) · Scope = new capabilities/markets (LinkedIn, Instagram, Whole Foods)' },
  { id: 'x-cash', deal: 0, front: 'When does all-cash win?', back: 'Target wants certainty · depressed stock · no exchange-ratio risk · bidder has liquidity/debt access (MS, Amazon, LVMH)' },
  { id: 'x-hostile', deal: 0, front: 'Hostile takeover example', back: 'Kraft–Cadbury: UK Takeover Panel · Somerdale controversy changed UK politics · eventual friendly acceptance' },
  { id: 'x-badwill', deal: 0, front: 'Badwill in banking', back: 'Buy below book value → negative goodwill · ECB: use profits to strengthen combined entity capital (CaixaBank–Bankia context)' },

  { id: 'l1-motives', lecture: 1, front: 'L1: Four acquisition motives  -  which creates value?', back: 'Only Efficiency/Synergies creates value · Market position = partial · Managers (hubris/agency) and Opportunity = destroy or neutral' },
  { id: 'l1-syn', lecture: 1, front: 'L1: Synergy equation', back: 'Value(A+B) = A + B + Synergies · Price = B + Control Premium (~35%) · Premium must be < Synergies for acquirer to gain' },
  { id: 'l1-types', lecture: 1, front: 'L1: Horizontal vs vertical vs diversification', back: 'Horizontal = high integration + antitrust + culture · Vertical = medium · Diversification = low synergies, low culture risk' },
  { id: 'l1-hardsoft', lecture: 1, front: 'L1: Hard vs soft synergies', back: 'Hard = cost (personnel, production, tax)  -  more reliable · Soft = revenue/cross-sell/market power  -  discount in analysis' },
  { id: 'l2-12', lecture: 2, front: 'L2: 12 acquisition phases (first & last)', back: '1 Business objectives → … → 8 Integration plan → 9 Due diligence → 10 Closing → 11 Integration → 12 Post-acquisition analysis' },
  { id: 'l2-dd', lecture: 2, front: 'L2: Integration plan vs due diligence order', back: 'Integration plan is Phase 8  -  BEFORE due diligence (Phase 9). DD verifies assumptions built into valuation and integration.' },
  { id: 'l2-ebitda', lecture: 2, front: 'L2: EBITDA multiple formula', back: 'Price = (Multiple × EBITDA) − Debt' },
  { id: 'l2-earn', lecture: 2, front: 'L2: Earn-out', back: 'Deferred payment tied to future performance (EBITDA, revenue, etc.) · Aligns incentives · Risk: buyer can influence metric' },
  { id: 'l2-curse', lecture: 2, front: 'L2: Winner\'s curse', back: 'In auctions, winner often overpays  -  always have walk-away price and discipline to use it' },
  { id: 'l3-hard', lecture: 3, front: 'L3: Hard vs soft post-acquisition problems', back: 'Hard = pre-deal (bad strategy, DD, price, synergies) · Soft = post-deal (culture, mgmt teams, communication)' },
  { id: 'l3-67', lecture: 3, front: 'L3: Manager turnover statistic', back: '~67% of acquired company managers leave within 4 years' },
  { id: 'l3-comm', lecture: 3, front: 'L3: Employee communication priority #1', back: '"Am I included in the new organization?"  -  before brand, strategy, or acquirer identity' },
  { id: 'l3-speed', lecture: 3, front: 'L3: Integration speed', back: 'Integrate rapidly  -  prolonged uncertainty kills retention and synergy delivery · Appoint Integration Manager' },
  { id: 'l5-newco', lecture: 5, front: 'L5: MBO Newco structure', back: 'Newco (mgmt + PE equity) → acquires target → merger by absorption → debt on target balance sheet' },
  { id: 'l5-formula', lecture: 5, front: 'L5: MBO exit value formula', back: 'Share value = (EBITDA × Exit Multiple) − Net Debt · Typical leverage 3–5× Debt/EBITDA' },
  { id: 'l5-7src', lecture: 5, front: 'L5: Seven sources of MBO value', back: 'Select target · Low entry price · Leverage · Ratchet terms · Optimise P&L · Optimise balance sheet · High exit multiple' },
  { id: 'l5-irr', lecture: 5, front: 'L5: PE target returns', back: 'IRR > 15% · Exit multiple ≥ 2× · Horizon 3–7 years' },
  { id: 'l6-220', lecture: 6, front: 'L6: PE fund economics', back: 'GP: 2% mgmt fee + 20% carry above ~8% hurdle · LP: passive, ~10-year commitment' },
  { id: 'l6-tag', lecture: 6, front: 'L6: Tag-along vs drag-along', back: 'Tag-along: minority joins majority sale · Drag-along: majority forces minority to sell in 100% deal' },
  { id: 'l7-hostile', lecture: 7, front: 'L7: Friendly vs hostile takeover', back: 'Friendly = board supports · Hostile = board opposes, bidder goes to shareholders · Hostile usually all-cash' },
  { id: 'l7-spain', lecture: 7, front: 'L7: Spain mandatory bid triggers', back: '>30% voting rights OR >50% board seats → must bid for 100%' },
  { id: 'l7-def', lecture: 7, front: 'L7: Key takeover defenses', back: 'Pre-bid: poison pill, golden parachutes, shark repellents · Post-bid: white knight, Pac-Man, legal action' },
  { id: 'l7-bear', lecture: 7, front: 'L7: Bear hug', back: 'Public offer so attractive board cannot refuse without shareholder revolt  -  most powerful single tactic' },
  { id: 'l8-cost', lecture: 8, front: 'L8: IPO costs', back: 'Direct: 5–10% of proceeds · Indirect undervaluation: 10–15% first-day pop' },
  { id: 'l8-green', lecture: 8, front: 'L8: Greenshoe', back: 'Over-allotment option ~15% extra shares · 1-month stabilisation period post-IPO' },
  { id: 'l8-firm', lecture: 8, front: 'L8: Firm commitment underwriting', back: 'Underwriter buys entire issue and resells  -  bears full risk (vs best efforts)' },
];
