const ALL_QUESTIONS = [
  { deal: 1, difficulty: 'easy', text: 'Microsoft paid how much for LinkedIn (total deal value)?', options: ['$13.7bn', '$19.5bn', '$26.2bn', '$71.3bn'], correct: 2, explanation: '$26.2bn all-cash — Microsoft\'s largest acquisition at the time, closed December 2016.' },
  { deal: 1, difficulty: 'medium', text: 'Why did LinkedIn prefer Microsoft\'s bid over Salesforce\'s?', options: ['Higher headline price only', 'All-cash with no financing condition vs cash+stock mix', 'Salesforce offered less cash', 'Microsoft promised to fire LinkedIn CEO'], correct: 1, explanation: 'Structure mattered: MS $196 all-cash vs SF $186 with stock — no exchange-ratio risk and certainty of close.' },
  { deal: 1, difficulty: 'medium', text: 'How did Microsoft primarily fund the LinkedIn acquisition?', options: ['Issued new equity', 'Repatriated offshore cash', '~$20bn corporate bond issuance', 'Asset sale of Nokia division'], correct: 2, explanation: 'Bonds at ~2% avoided depleting offshore cash and 35% repatriation tax.' },
  { deal: 1, difficulty: 'hard', text: 'Microsoft–LinkedIn is best classified as which deal type?', options: ['Scale/cost synergy merger', 'Scope/capability acquisition', 'Distressed turnaround', 'Reverse takeover'], correct: 1, explanation: 'Scope deal — professional data graph, cloud, CRM integration; not primarily cost-cutting.' },
  { deal: 1, difficulty: 'easy', text: 'What premium did Microsoft pay over LinkedIn\'s pre-deal close price?', options: ['20%', '34.2%', '49.5%', '~50%'], correct: 2, explanation: '49.5% premium at $196/share vs June 10, 2016 close.' },
  { deal: 1, difficulty: 'medium', text: 'Post-acquisition, Microsoft applied which integration approach to LinkedIn?', options: ['Full assimilation like Nokia', 'Federated autonomy — separate brand, CEO retained', 'Immediate shutdown of LinkedIn platform', 'Spin-off within 2 years'], correct: 1, explanation: 'Jeff Weiner stayed CEO; LinkedIn identity preserved — lesson from Nokia failure.' },

  { deal: 2, difficulty: 'easy', text: 'CaixaBank–Bankia was structured as:', options: ['All-cash tender offer', 'All-share merger by absorption', 'Hostile takeover', 'Asset carve-out only'], correct: 1, explanation: 'CaixaBank absorbed Bankia; exchange ratio 0.6845 CBK shares per Bankia share.' },
  { deal: 2, difficulty: 'medium', text: 'A key driver of Spanish bank consolidation in 2020 was:', options: ['Rising interest rates boosting NIM', 'Branch overcapacity and negative ECB deposit rates', 'Mandatory EU cross-border mergers', 'Cryptocurrency disruption'], correct: 1, explanation: 'Structural profitability crisis: negative rates, excess branches, COVID provisions.' },
  { deal: 2, difficulty: 'medium', text: 'Bankia was formed and later nationalised because:', options: ['It acquired Twitter', 'Merger of savings banks + real estate losses → 2012 bailout', 'Hostile bid from BBVA', 'IPO failure in 2020'], correct: 1, explanation: 'Seven cajas merged 2010; nationalised 2012 after €22.4bn bailout; FROB held ~61.8%.' },
  { deal: 2, difficulty: 'easy', text: 'The combined CaixaBank–Bankia entity became:', options: ['Spain\'s 3rd largest bank', 'Spain\'s largest domestic bank by assets', 'A Portuguese-only bank', 'A private equity fund'], correct: 1, explanation: '>€660bn assets, >20M customers — largest domestic Spanish bank.' },
  { deal: 2, difficulty: 'hard', text: 'The ECB\'s 2021 consolidation stance mattered because:', options: ['It banned all mergers', 'Credible integration plans not auto-penalised; badwill can strengthen capital', 'It required 100% cash consideration', 'It forced cross-border deals only'], correct: 1, explanation: 'ECB supervisory guide supported domestic scale deals with proper integration plans.' },

  { deal: 3, difficulty: 'easy', text: 'Amazon acquired Whole Foods for approximately:', options: ['$1bn', '$13.7bn', '$26.2bn', '$15.8bn'], correct: 1, explanation: '$13.7bn all-cash, announced June 2017.' },
  { deal: 3, difficulty: 'medium', text: 'Whole Foods represented what share of Amazon\'s 2017 revenue?', options: ['Over 25%', 'About 15%', 'Less than 4%', 'Exactly 50%'], correct: 2, explanation: 'WFM ~$16bn revenue vs Amazon ~$136bn — infrastructure play, not earnings engine.' },
  { deal: 3, difficulty: 'medium', text: 'Which activist investor pressured Whole Foods before the Amazon deal?', options: ['Nelson Peltz / Trian', 'JANA Partners', 'Carl Icahn', 'Elliott Management'], correct: 1, explanation: 'JANA built 8.8% stake pushing for strategic review/sale.' },
  { deal: 3, difficulty: 'easy', text: 'Amazon–Whole Foods is primarily a:', options: ['Scale/cost-cutting merger', 'Scope/vertical integration deal', 'Distressed debt purchase', 'Joint venture'], correct: 1, explanation: 'Scope — physical grocery footprint, omnichannel, last-mile; catalysed sector digital response.' },
  { deal: 3, difficulty: 'hard', text: 'A major post-deal industry effect was:', options: ['Grocery went 100% offline', 'Competitors accelerated omnichannel (Target/Shipt, Kroger/Ocado)', 'Whole Foods closed all stores', 'Amazon exited retail'], correct: 1, explanation: 'Deal reshaped competitive response — Walmart, Target, Kroger built delivery capabilities.' },

  { deal: 4, difficulty: 'easy', text: 'Facebook acquired Instagram in:', options: ['2008', '2012', '2016', '2019'], correct: 1, explanation: 'Announced April 9, 2012; closed September 2012 — 5 weeks before FB IPO.' },
  { deal: 4, difficulty: 'medium', text: 'At acquisition, Instagram had:', options: ['$2bn revenue and 500 employees', 'Zero revenue, ~13 employees, 30M+ users', 'Been public for 5 years', 'Been owned by Google'], correct: 1, explanation: 'Pre-revenue mobile photo app — valuation on strategic optionality and users.' },
  { deal: 4, difficulty: 'medium', text: 'Instagram consideration structure was:', options: ['100% cash', '$300m cash + 23M Facebook shares', 'All-stock swap only', 'Earn-out over 10 years'], correct: 1, explanation: 'Mixed consideration; ~$1bn announced, ~$715m at close as FB share price moved.' },
  { deal: 4, difficulty: 'hard', text: 'Facebook\'s integration strategy for Instagram was:', options: ['Rebrand immediately as Facebook Photos', 'Deferred integration — separate brand preserved', 'Shut down Instagram within 1 year', 'Merge engineering teams day one'], correct: 1, explanation: 'Preserved brand; founders stayed 6 years; among best M&A outcomes in history.' },
  { deal: 4, difficulty: 'easy', text: 'A competing bidder for Instagram was reportedly:', options: ['Microsoft at $26bn', 'Twitter at ~$525M', 'Yahoo at $12.5bn', 'Amazon at $13.7bn'], correct: 1, explanation: 'Zuckerberg moved quickly in a weekend partly to pre-empt Twitter.' },

  { deal: 5, difficulty: 'easy', text: 'Kraft acquired Cadbury for approximately:', options: ['$9.7bn', '$19.5bn', '$26.2bn', '$71.3bn'], correct: 1, explanation: 'Completed February 2010 at ~$19.5bn after hostile bidding process.' },
  { deal: 5, difficulty: 'medium', text: 'Which prior deal made Cadbury the only large independent confectionery target?', options: ['Disney–Fox', 'Mars–Wrigley ($23bn, 2008)', 'Amazon–Whole Foods', 'LVMH–Tiffany'], correct: 1, explanation: 'Mars absorbed Wrigley; Cadbury was structurally the last major independent.' },
  { deal: 5, difficulty: 'medium', text: 'The Somerdale controversy involved:', options: ['A plant closure reversal after promises to keep it open', 'A failed IPO', 'An antitrust block', 'Currency hedging losses'], correct: 0, explanation: 'Kraft reversed pledge on Bristol plant — damaged trust and UK takeover politics.' },
  { deal: 5, difficulty: 'hard', text: 'Kraft–Cadbury outcome for shareholders was:', options: ['Both sides won long-term', 'Cadbury SH gained ~50%; Kraft SH short-term negative; Mondelez spin 2012', 'Both lost everything', 'Only Kraft SH gained'], correct: 1, explanation: 'Strategically right direction, too expensive, poor integration — classic hubris case.' },
  { deal: 5, difficulty: 'medium', text: 'Cadbury\'s most valuable geographic asset for Kraft was:', options: ['UK manufacturing only', 'India distribution network (~70% share in segments)', 'US fast food', 'Australian mining'], correct: 1, explanation: 'Decades-built tier-2/3 city distribution in India — hard to replicate organically.' },
  { deal: 5, difficulty: 'easy', text: 'Kraft\'s bid for Cadbury began as:', options: ['Friendly merger agreed in 1 day', 'Hostile approach later raised to friendly acceptance', 'Government-mandated merger', 'A joint venture'], correct: 1, explanation: 'Sept 2009 rejected → Nov 2009 hostile → Jan 2010 raised bid → Feb 2010 accepted.' },

  { deal: 6, difficulty: 'easy', text: 'Disney\'s final price for 21st Century Fox assets was:', options: ['$52.4bn', '$65bn', '$71.3bn', '$85bn'], correct: 2, explanation: 'Raised after Comcast counterbid; closed March 2019.' },
  { deal: 6, difficulty: 'medium', text: 'Which assets did Murdoch KEEP (not sold to Disney)?', options: ['X-Men and Avatar', 'Fox News, Fox Broadcasting, Fox Sports', 'Star India', 'National Geographic'], correct: 1, explanation: 'New Fox Corporation — news and live sports not easily disrupted by streaming.' },
  { deal: 6, difficulty: 'medium', text: 'Comcast\'s counterbid forced Disney to:', options: ['Withdraw entirely', 'Add a cash component to the offer', 'Sell ESPN', 'Merge with Netflix'], correct: 1, explanation: 'May 2018 Comcast $65bn all-cash → Disney raised to $71.3bn cash+stock.' },
  { deal: 6, difficulty: 'hard', text: 'The primary sector force behind Disney–Fox was:', options: ['Rising cable subscriptions', 'Streaming disruption and IP/content scarcity', 'Declining content budgets', 'Government regulation of parks'], correct: 1, explanation: 'Netflix growth destroyed bundle economics; deep IP libraries became strategic assets.' },
  { deal: 6, difficulty: 'easy', text: 'Disney initiated the Fox deal through:', options: ['Public auction run by Goldman', 'Direct CEO-to-CEO conversation (Iger–Murdoch)', 'Hostile tender offer', 'Bankruptcy court'], correct: 1, explanation: 'Late 2017 private approach — fully friendly, no hostile resistance.' },

  { deal: 7, difficulty: 'easy', text: 'Marriott–Starwood closed in:', options: ['November 2015', 'September 2016', 'March 2019', 'January 2021'], correct: 1, explanation: 'Agreement Nov 2015; Anbang disruption Mar 2016; closed Sep 23, 2016.' },
  { deal: 7, difficulty: 'medium', text: 'Starwood\'s loyalty program (SPG) mattered because:', options: ['It owned airlines', '50% of room nights; core moat vs OTAs and Airbnb', 'It was loss-making with no members', 'It was being shut down pre-deal'], correct: 1, explanation: 'SPG drove direct bookings and was a key strategic asset for Marriott.' },
  { deal: 7, difficulty: 'medium', text: 'Who made a competing bid for Starwood in March 2016?', options: ['Anbang Insurance consortium', 'Airbnb', 'Hilton only', 'LVMH'], correct: 0, explanation: 'Chinese Anbang bid forced Marriott to raise to 0.80 shares + $21 cash.' },
  { deal: 7, difficulty: 'easy', text: 'Combined Marriott–Starwood became:', options: ['5th largest hotel company', 'Largest hotel company globally (~5,700 properties)', 'A cruise line', 'An OTA platform'], correct: 1, explanation: '1.1 million rooms across 110+ countries.' },
  { deal: 7, difficulty: 'hard', text: 'Marriott and Starwood share which business model trait?', options: ['Own most hotel real estate', 'Asset-light — franchise and management fees', 'Only operate in North America', 'No loyalty programs'], correct: 1, explanation: 'Both pivoted to asset-light; synergies in systems and G&A, not property.' },

  { deal: 8, difficulty: 'easy', text: 'The VW–Porsche saga is unusual because:', options: ['It was a friendly cash merger with no drama', 'Porsche tried to buy VW but ended up being absorbed by VW', 'VW was acquired by Toyota', 'Family had no involvement'], correct: 1, explanation: 'Reverse outcome — bidder became target after options debt and GFC.' },
  { deal: 8, difficulty: 'medium', text: 'Porsche\'s options strategy left it with approximately how much debt?', options: ['€700m', '~€14bn', '$26.2bn', 'Zero debt'], correct: 1, explanation: 'Cash-settled options on VW shares; credit markets froze in 2008–09.' },
  { deal: 8, difficulty: 'medium', text: 'After the deal, who still controls Volkswagen voting rights?', options: ['German government only', 'Porsche SE / Porsche-Piëch family (~50.7%)', 'Public float 100%', 'Toyota'], correct: 1, explanation: 'Porsche SE holding company retains majority VW voting shares.' },
  { deal: 8, difficulty: 'hard', text: 'Porsche\'s ~22.8% RoE vs VW\'s ~3.0% (2005) explains:', options: ['Why VW wanted to exit autos', 'Why Porsche pursued control and why carrying values diverged from cash paid', 'Why Porsche filed bankruptcy', 'Why the deal was blocked by EU'], correct: 1, explanation: 'Return asymmetry drove options strategy and accounting complexity.' },
  { deal: 8, difficulty: 'medium', text: 'The October 2008 "short squeeze" involved:', options: ['Porsche revealing ~74.1% effective VW stake', 'Instagram IPO', 'Bankia nationalisation', 'Tiffany litigation'], correct: 0, explanation: 'Disclosure briefly made VW the world\'s most valuable company.' },

  { deal: 9, difficulty: 'easy', text: 'LVMH acquired Tiffany for a total of:', options: ['$3.2bn', '$15.8bn', '$71.3bn', '$1bn'], correct: 1, explanation: 'Largest luxury deal ever; closed January 2021.' },
  { deal: 9, difficulty: 'medium', text: 'The final Tiffany price per share after renegotiation was:', options: ['$98', '$120', '$131.50', '$196'], correct: 2, explanation: '$135 signed Nov 2019 → litigation → $131.50 Oct 2020.' },
  { deal: 9, difficulty: 'medium', text: 'LVMH\'s main strategic gap Tiffany filled was:', options: ['Fashion & leather dominance', 'Underweight Watches & Jewellery vs Richemont/Cartier', 'US wine production', 'Airline loyalty'], correct: 1, explanation: 'Jewellery was ~8% of LVMH vs 44% Fashion & Leather — hard luxury push.' },
  { deal: 9, difficulty: 'hard', text: 'The Sep 2020 LVMH–Tiffany dispute centred on:', options: ['CEO personal feud only', 'LVMH attempting withdrawal citing pandemic; Tiffany lawsuit; renegotiation', 'EU blocking the deal', 'Stock-based consideration failure'], correct: 1, explanation: 'MAC/force majeure arguments → litigation → $425M price reduction.' },
  { deal: 9, difficulty: 'easy', text: 'Tiffany financing at close was:', options: ['All-stock', 'All-cash (bonds + cash reserves)', 'Merger of equals', 'Seller financing only'], correct: 1, explanation: '€10bn bond issuance + €5bn cash — 100% share acquisition.' },

  { deal: 0, difficulty: 'medium', text: 'Which pair are both primarily SCALE deals?', options: ['Instagram + LinkedIn', 'CaixaBank–Bankia + Marriott–Starwood', 'Whole Foods + Tiffany', 'Porsche + Instagram'], correct: 1, explanation: 'Banking and hotels: same industry, cost synergies, market share.' },
  { deal: 0, difficulty: 'medium', text: 'Which deals used ALL-CASH consideration?', options: ['CaixaBank–Bankia and Marriott–Starwood only', 'Microsoft–LinkedIn, Amazon–WFM, and LVMH–Tiffany', 'Kraft–Cadbury and Disney–Fox only', 'VW–Porsche and Instagram only'], correct: 1, explanation: 'MS, Amazon, LVMH all-cash; others mixed or all-share.' },
  { deal: 0, difficulty: 'hard', text: 'A HOSTILE bid that eventually completed friendly was:', options: ['Disney–Fox', 'Kraft–Cadbury', 'Microsoft–LinkedIn', 'LVMH–Tiffany'], correct: 1, explanation: 'Kraft hostile Nov 2009 → raised bid → Cadbury accepted Feb 2010.' },
  { deal: 0, difficulty: 'easy', text: 'The largest deal by value in this set is:', options: ['Microsoft–LinkedIn', 'Disney–21st Century Fox', 'Facebook–Instagram', 'CaixaBank–Bankia'], correct: 1, explanation: '$71.3bn — media consolidation wave 2017–19.' },

  // —— Lecture 1: Introduction ——
  { lecture: 1, difficulty: 'easy', text: 'According to the course, which acquisition motive truly creates economic value?', options: ['Market position / market power', 'Efficiency and synergies', 'Managerial hubris', 'Opportunity / buying cheap'], correct: 1, explanation: 'Only synergies create value; market power redistributes; managers/opportunity destroy or fail to create value.' },
  { lecture: 1, difficulty: 'medium', text: 'The synergy value equation requires that:', options: ['Control premium exceeds synergies', 'Control premium is less than synergies', 'Price equals book value', 'Soft synergies always exceed hard synergies'], correct: 1, explanation: 'Value(A+B) = A + B + Synergies; Price = B + Premium. Acquirer gains only if Premium < Synergies.' },
  { lecture: 1, difficulty: 'easy', text: 'Average control premium in US takeover studies is approximately:', options: ['10%', '20%', '35%', '50%'], correct: 2, explanation: 'Course cites ~35% average control premium.' },
  { lecture: 1, difficulty: 'medium', text: 'Which deal type has the HIGHEST cultural integration risk?', options: ['Diversification', 'Vertical integration', 'Horizontal integration', 'Joint venture'], correct: 2, explanation: 'Horizontal = same sector, direct competitors, distinct identities → highest cultural conflict and antitrust scrutiny.' },
  { lecture: 1, difficulty: 'hard', text: 'Hard synergies are generally preferred in analysis because:', options: ['They are always larger in euro terms', 'They are more measurable and reliable than revenue synergies', 'They require no integration', 'They avoid antitrust review'], correct: 1, explanation: 'Cost synergies (personnel, production, tax) are more predictable; soft/revenue synergies should be discounted.' },
  { lecture: 1, difficulty: 'medium', text: 'A merger differs from a 100% acquisition because:', options: ['It uses only cash consideration', 'It fully integrates into one legal entity; reversal requires spin-off', 'It never requires shareholder approval', 'It cannot create synergies'], correct: 1, explanation: 'Merger = highest commitment level on the legal forms ladder.' },
  { lecture: 1, difficulty: 'easy', text: 'External (inorganic) growth is primarily chosen when:', options: ['Culture must stay homogeneous', 'Speed and critical mass matter in consolidating markets', 'The company has no access to debt', 'Synergies are impossible'], correct: 1, explanation: 'Buy-and-build is faster when time and scale matter — but carries integration risk.' },

  // —— Lecture 2: Acquisition Process ——
  { lecture: 2, difficulty: 'easy', text: 'How many phases does the course acquisition process have?', options: ['8', '10', '12', '15'], correct: 2, explanation: '12 phases from business objectives through post-acquisition analysis.' },
  { lecture: 2, difficulty: 'medium', text: 'In the 12-phase process, integration planning comes:', options: ['After post-acquisition analysis', 'Before due diligence', 'After closing only', 'Before first contact'], correct: 1, explanation: 'Phase 8 = integration plan; Phase 9 = due diligence. DD verifies integration and synergy assumptions.' },
  { lecture: 2, difficulty: 'medium', text: 'The EBITDA multiple valuation formula is:', options: ['Price = Multiple × Revenue', 'Price = (Multiple × EBITDA) − Debt', 'Price = EBITDA / WACC', 'Price = Book value + Premium'], correct: 1, explanation: 'Standard course formula for multiple-based valuation.' },
  { lecture: 2, difficulty: 'hard', text: '"Winner\'s curse" in M&A refers to:', options: ['Target shareholders losing in a friendly deal', 'Auction winner often overpaying', 'Earn-out always favouring the seller', 'Due diligence finding too few problems'], correct: 1, explanation: 'Competitive auctions push the winner to pay more than value — classic negotiation trap.' },
  { lecture: 2, difficulty: 'medium', text: 'An earn-out aligns incentives but risks conflict because:', options: ['It is always paid in stock', 'The buyer may influence the performance metric post-close', 'It is illegal in the EU', 'It replaces due diligence'], correct: 1, explanation: 'Deferred payment tied to EBITDA/revenue etc. — buyer actions can affect the metric.' },
  { lecture: 2, difficulty: 'easy', text: 'In a share purchase (vs asset purchase), the buyer:', options: ['Avoids all liabilities', 'Acquires everything including contingent liabilities', 'Cannot use tax credits', 'Only buys selected patents'], correct: 1, explanation: 'Share deal = full succession of liabilities; asset deal = cherry-pick but may lose tax credits.' },
  { lecture: 2, difficulty: 'medium', text: 'The Letter of Intent (LOI) is typically:', options: ['Fully binding like the SPA', 'A non-binding framework before due diligence', 'Filed only with regulators', 'Used only in hostile takeovers'], correct: 1, explanation: 'LOI/MOU sets indicative terms, exclusivity, DD timeline — not the final binding contract.' },

  // —— Lecture 3: Post-Acquisition ——
  { lecture: 3, difficulty: 'easy', text: 'Post-acquisition "hard problems" are mainly:', options: ['Communication failures', 'Pre-deal failures: bad strategy, DD, pricing, synergy assumptions', 'Only cultural issues', 'Regulatory delays only'], correct: 1, explanation: 'Hard = structural/pre-deal; soft = culture, management, communication post-close.' },
  { lecture: 3, difficulty: 'medium', text: 'Approximately what % of acquired company managers leave within 4 years?', options: ['17%', '35%', '67%', '90%'], correct: 2, explanation: 'Course statistic: ~67% manager turnover in acquired firm within 4 years.' },
  { lecture: 3, difficulty: 'medium', text: 'Employees\' FIRST priority in merger communication is:', options: ['Who is the acquirer?', 'Am I included in the new organization?', 'What is the acquirer\'s stock price?', 'Will the brand change?'], correct: 1, explanation: 'Job security and role inclusion come before strategic narrative.' },
  { lecture: 3, difficulty: 'hard', text: 'Integration should be carried out rapidly because:', options: ['Regulators require it', 'Prolonged uncertainty destroys retention and synergy delivery', 'It eliminates the need for communication', 'It avoids all cultural conflict'], correct: 1, explanation: 'Momentum for change; uncertainty is worse than bad news.' },
  { lecture: 3, difficulty: 'easy', text: 'Cultural conflict risk is LOWEST in:', options: ['Horizontal mergers', 'Vertical mergers', 'Diversification deals', 'Hostile takeovers only'], correct: 2, explanation: 'Diversification = minimal operational overlap → lowest cultural collision.' },
  { lecture: 3, difficulty: 'medium', text: 'An Integration Manager\'s role is to:', options: ['Replace the CEO permanently', 'Supervise the full integration process dedicatedly', 'Handle only HR payroll', 'Negotiate the SPA'], correct: 1, explanation: 'One of six integration guidelines — dedicated integration leadership.' },

  // —— Lecture 5: MBOs ——
  { lecture: 5, difficulty: 'easy', text: 'In an MBO, who typically buys the company?', options: ['A hostile competitor', 'Existing management team', 'Government regulator', 'Retail shareholders only'], correct: 1, explanation: 'MBO = Management Buyout; managers know the business (lower risk than MBI).' },
  { lecture: 5, difficulty: 'medium', text: 'After the Newco structure, acquisition debt sits on:', options: ['The PE fund only', 'The target company\'s balance sheet (post-merger by absorption)', 'The seller\'s balance sheet', 'A government guarantee fund'], correct: 1, explanation: 'Newco buys target, then merges into target — levered balance sheet at operating company.' },
  { lecture: 5, difficulty: 'medium', text: 'Typical post-MBO Debt/EBITDA leverage is:', options: ['0.5–1×', '3–5×', '10–15×', 'No debt is used'], correct: 1, explanation: 'Course range: 3–5× vs often <1× pre-deal.' },
  { lecture: 5, difficulty: 'hard', text: 'MBO equity value at exit is calculated as:', options: ['Revenue × P/E only', '(EBITDA × Exit Multiple) − Net Debt', 'Book value + goodwill', 'DCF with no debt'], correct: 1, explanation: 'Core MBO profitability formula from Lecture 5.' },
  { lecture: 5, difficulty: 'medium', text: 'An equity ratchet:', options: ['Reduces management equity if performance is poor', 'Increases management\'s equity % if IRR/multiple thresholds are exceeded', 'Is a type of poison pill', 'Replaces senior debt'], correct: 1, explanation: 'Aligns managers with PE investors on outperformance.' },
  { lecture: 5, difficulty: 'easy', text: 'PE investors typically target an IRR of at least:', options: ['5%', '10%', '15%', '50%'], correct: 2, explanation: 'Course: IRR > 15%, exit multiple ≥ 2×, horizon 3–7 years.' },
  { lecture: 5, difficulty: 'medium', text: 'A Secondary Buyout (SBO) is:', options: ['Management buying from family', 'One PE fund selling to another PE fund', 'IPO of the target', 'Government privatisation'], correct: 1, explanation: 'Common PE exit route — SBO.' },

  // —— Lecture 6: PE & VC ——
  { lecture: 6, difficulty: 'easy', text: 'In a PE fund, the GP earns:', options: ['Only a fixed salary', '2% management fee + 20% carried interest above hurdle', '100% of profits', 'Nothing until IPO'], correct: 1, explanation: 'Classic "2 and 20" structure with ~8% hurdle rate.' },
  { lecture: 6, difficulty: 'medium', text: 'Limited Partners (LPs) in a PE fund:', options: ['Manage day-to-day operations', 'Commit capital passively for ~10 years', 'Must hold >50% voting rights', 'Are always the management team'], correct: 1, explanation: 'LPs = pension funds, insurers, etc. — passive capital providers.' },
  { lecture: 6, difficulty: 'medium', text: 'Tag-along rights allow a minority investor to:', options: ['Block any sale', 'Join a majority shareholder\'s sale on the same terms', 'Force an IPO', 'Reduce debt covenants'], correct: 1, explanation: 'Protects minority if majority sells.' },
  { lecture: 6, difficulty: 'medium', text: 'Drag-along rights allow a majority investor to:', options: ['Prevent any exit', 'Force minority shareholders to sell in a 100% sale', 'Increase management fees', 'Avoid due diligence'], correct: 1, explanation: 'Ensures buyer can acquire 100% when majority has a deal.' },
  { lecture: 6, difficulty: 'easy', text: 'Business angels typically invest:', options: ['>€50M in mature utilities', '<€1M at seed/start-up stage', 'Only via leveraged buyouts', 'Only in listed companies'], correct: 1, explanation: 'Angels = individuals, early stage, hands-on, small tickets.' },
  { lecture: 6, difficulty: 'hard', text: 'Expansion capital differs from an MBO because:', options: ['It never uses PE', 'It is usually minority/majority growth capital with board governance, not full leveraged buyout of the company', 'It has no exit', 'It is only for distressed firms'], correct: 1, explanation: 'Expansion = growth financing with veto rights; MBO = leveraged change of control.' },

  // —— Lecture 7: Takeovers ——
  { lecture: 7, difficulty: 'easy', text: 'A hostile takeover is one where:', options: ['The board supports the bid', 'The board opposes and the bidder goes to shareholders', 'No premium is paid', 'Only stock consideration is used'], correct: 1, explanation: 'Friendly = board support; hostile = board resistance, direct shareholder appeal.' },
  { lecture: 7, difficulty: 'medium', text: 'In Spain, crossing 30% voting rights triggers:', options: ['Automatic delisting', 'Mandatory bid for 100%', 'A poison pill by law', 'No regulatory action'], correct: 1, explanation: 'Spanish mandatory takeover rules: >30% voting or >50% board seats → bid for 100%.' },
  { lecture: 7, difficulty: 'medium', text: 'A poison pill defence works by:', options: ['Selling crown jewels', 'Issuing discounted shares to existing SH when threshold crossed, diluting acquirer', 'Paying executives to leave', 'Buying the attacker'], correct: 1, explanation: 'Classic pre-bid defence — buys time, dilutes hostile bidder.' },
  { lecture: 7, difficulty: 'medium', text: 'A "bear hug" is:', options: ['A Pac-Man defence', 'A public offer so attractive the board risks shareholder revolt if they refuse', 'Insider trading', 'A type of earn-out'], correct: 1, explanation: 'Forces board dilemma: accept or face angry shareholders.' },
  { lecture: 7, difficulty: 'hard', text: 'Pac-Man defence means:', options: ['Selling to a White Knight', 'The target bids to acquire the hostile attacker', 'Issuing golden parachutes', 'Leveraging the balance sheet'], correct: 1, explanation: 'Post-bid defence — role reversal.' },
  { lecture: 7, difficulty: 'medium', text: 'Hostile targets often have:', options: ['Low free float and concentrated ownership', 'Broad dispersed shareholder base and depressed stock price', 'Mandatory board support', 'No synergies with bidder'], correct: 1, explanation: 'Dispersed ownership easier to accumulate; weak performance → hidden value thesis.' },
  { lecture: 7, difficulty: 'easy', text: 'A White Knight is:', options: ['The hostile bidder', 'A friendly third-party acquirer invited to make a competing bid', 'A regulator', 'An investment bank'], correct: 1, explanation: 'Post-bid defence — alternative buyer preferred by target board.' },

  // —— Lecture 8: IPO ——
  { lecture: 8, difficulty: 'easy', text: 'An IPO is:', options: ['A mandatory takeover', 'First public offering of a company\'s shares', 'A management buyout', 'A bond issuance only'], correct: 1, explanation: 'Initial Public Offering — first time shares offered to public.' },
  { lecture: 8, difficulty: 'medium', text: 'Typical direct IPO costs are:', options: ['0.5–1% of proceeds', '5–10% of proceeds', '25–30% of proceeds', 'Zero'], correct: 1, explanation: 'Underwriters, auditors, marketing — plus 10–15% indirect undervaluation.' },
  { lecture: 8, difficulty: 'medium', text: 'The greenshoe (over-allotment) option allows:', options: ['Founders to sell extra shares privately', 'Underwriters to issue up to ~15% more shares to stabilise post-IPO price', 'Poison pill activation', 'Mandatory delisting'], correct: 1, explanation: '1-month stabilisation period tool after IPO.' },
  { lecture: 8, difficulty: 'hard', text: 'Firm commitment underwriting means:', options: ['Underwriter sells what it can with no risk', 'Underwriter buys the entire issue and resells — bears full risk', 'Company self-distributes only', 'Deal is cancelled if 50% not sold'], correct: 1, explanation: 'vs best efforts (no purchase commitment) and all-or-none.' },
  { lecture: 8, difficulty: 'medium', text: 'Book-building in an IPO:', options: ['Sets price from institutional demand during road show', 'Eliminates all undervaluation', 'Replaces the prospectus', 'Is only used in hostile takeovers'], correct: 0, explanation: 'Price discovery from institutional investor indications.' },
  { lecture: 8, difficulty: 'easy', text: 'A primary IPO offering:', options: ['Only existing shareholders sell — no new capital', 'Company issues new shares and raises capital', 'Is always a carve-out', 'Requires no regulator approval'], correct: 1, explanation: 'Primary = new shares/money to company; secondary = existing SH liquidity.' },
  { lecture: 8, difficulty: 'medium', text: 'The "first-day pop" in IPOs represents:', options: ['Free profit for the company', 'Structural undervaluation cost (~10–15%) to attract investors', 'Illegal market manipulation', 'Earn-out payment'], correct: 1, explanation: 'Course: indirect cost of going public — shares priced below trading level.' },
];
