const DEAL_LABELS = {
  1: 'Microsoft–LinkedIn',
  2: 'CaixaBank–Bankia',
  3: 'Amazon–Whole Foods',
  4: 'Facebook–Instagram',
  5: 'Kraft–Cadbury',
  6: 'Disney–21st Century Fox',
  7: 'Marriott–Starwood',
  8: 'VW–Porsche',
  9: 'LVMH–Tiffany',
};

const STUDY_DEALS = [
  {
    id: 1,
    title: 'Microsoft — LinkedIn',
    year: 2016,
    value: '$26.2bn',
    closed: 'Dec 2016',
    dealType: 'Friendly auction',
    consideration: 'All-cash ($196/share)',
    premium: '49.5%',
    sector: 'Tech / SaaS / professional data',
    motive: 'Scope — data, cloud, CRM',
    summary: 'Microsoft\'s largest acquisition: all-cash purchase of LinkedIn at $196/share (49.5% premium), financed by ~$20bn bond issuance to avoid repatriating offshore cash. Scope deal for professional identity data, Dynamics 365 integration, and blocking Salesforce.',
    sections: [
      { h: 'Sector context', html: '<p>2016 tech M&A hit ~$467bn driven by <strong>cloud shift</strong>, <strong>data as asset</strong>, and <strong>scope over scale</strong>. Largest pure-software deal of the year; comparable to Oracle–NetSuite, SoftBank–ARM.</p>' },
      { h: 'Acquirer', html: '<p>Nadella\'s "cloud-first" pivot after Nokia ($7.2bn) and aQuantive ($6.2bn write-down) failures. Prior wins: Skype → Teams foundation, Mojang. Held &gt;$100bn offshore cash.</p>' },
      { h: 'Target', html: '<p>433M members; Talent Solutions 65% of revenue. 13 years of structured professional data ("Economic Graph"). Net margin −5.5% in 2015 — structurally unprofitable standalone.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Microsoft:</strong> Identity-aware ecosystem; Office/Teams/Dynamics + LinkedIn data; block Salesforce</li><li><strong>LinkedIn:</strong> Azure migration cuts capex; enterprise distribution via MS sales force; federated autonomy (Weiner stayed CEO)</li></ul>' },
      { h: 'Deal process', html: '<p>Nadella approached Weiner Feb 2016. Bidders: Microsoft, Salesforce, Google, Party C. Facebook withdrew. Best-and-final: MS <strong>$196 all-cash</strong> vs Salesforce <strong>$186 cash+stock</strong>. All-cash won — no exchange-ratio risk, no financing condition.</p>' },
      { h: 'Valuation', html: '<p>EV/Revenue 8.76× (FY2015 $2,991M rev); EV/EBITDA 33.6×. $10bn bidding premium vs standalone ~$16.2bn. Termination fees: $725M each side (symmetric — MS absorbed EC risk).</p>' },
      { h: 'Post-deal', html: '<p>Members 500M→825M by 2020. Synergies: Sales Navigator + Dynamics (12–15% productivity), Azure migration ($150M run-rate by 2018). Federated integration — opposite of Nokia failure. Shares −3% on announcement.</p>' },
    ],
    traps: ['All-cash vs Salesforce stock mix — structure mattered as much as price', 'Scope deal (capabilities/data), not cost-cutting', '$20bn bonds at ~2% vs 35% repatriation tax', 'Nokia lesson → kept LinkedIn brand & CEO autonomy'],
  },
  {
    id: 2,
    title: 'CaixaBank — Bankia',
    year: '2020–21',
    value: '~€4.3bn equity',
    closed: 'Mar 2021',
    dealType: 'Friendly merger by absorption',
    consideration: 'All-share (0.6845 CBK per Bankia share)',
    premium: '20% over unaffected ratio',
    sector: 'Spanish retail banking',
    motive: 'Scale + cost synergies',
    summary: 'All-share domestic banking merger creating Spain\'s largest bank (~€660bn assets, 20M+ customers). Driven by negative rates, branch overcapacity, COVID provisions, and ECB support for consolidation.',
    sections: [
      { h: 'Sector context', html: '<p>Spanish banks under structural pressure: ECB negative deposit rate compressed NIM; branches fell 45,662 (2008) → 23,340 (2020). H1 2020: €26.5bn provisions, sector loss €11.5bn. Domestic consolidation extracts branch/IT synergies better than cross-border.</p>' },
      { h: 'Acquirer — CaixaBank', html: '<p>Listed successor to "la Caixa". Strong retail, bancassurance, asset management. Prior M&A: Banca Cívica (2012), Banco de Valencia (2013), Barclays Spain (2014), BPI Portugal (2017).</p>' },
      { h: 'Target — Bankia', html: '<p>Formed 2010 from merger of seven savings banks. Nationalised 2012 after €22.4bn bailout. State (FROB) held ~61.8% at deal — <strong>state exit set the clock</strong>. Distressed but large deposit franchise.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>CaixaBank:</strong> Scale first (defend ROE), scope second (fee income cross-sell), regulatory power as by-product</li><li><strong>Bankia:</strong> Friendly cover for distressed fundamentals; state exit</li><li><strong>Deal type:</strong> In-market merger — overlapping branches, IT, admin</li></ul>' },
      { h: 'Structure & valuation', html: '<p>CaixaBank absorbs Bankia. Exchange ratio 0.6845 new CBK shares per Bankia share. Combined: #1 Spain by domestic assets, ~€368bn loan book. ECB guide (Jan 2021): integration plans not auto-penalised; badwill profits strengthen capital.</p>' },
      { h: 'Post-deal', html: '<p>Cost synergies from branch closures and platform integration. Comparable wave: Intesa/UBI (Italy), Unicaja/Liberbank (Spain). BBVA–Sabadell explored but abandoned.</p>' },
    ],
    traps: ['All-share, not cash — no liquidity event for Bankia holders beyond premium in ratio', 'Badwill / negative goodwill possible when buying below book', 'State seller (FROB) — political timing mattered', 'COVID accelerated consolidation logic'],
  },
  {
    id: 3,
    title: 'Amazon — Whole Foods',
    year: 2017,
    value: '$13.7bn',
    closed: 'Aug 2017',
    dealType: 'Friendly / negotiated',
    consideration: 'All-cash ($42/share)',
    premium: '~27%',
    sector: 'US grocery / omnichannel retail',
    motive: 'Scope — physical grocery footprint',
    summary: 'Amazon\'s entry into physical grocery: $13.7bn all-cash for 456 stores. Strategic option on omnichannel and last-mile — WFM was &lt;4% of Amazon revenue; deal bought infrastructure, not earnings.',
    sections: [
      { h: 'Sector context', html: '<p>US grocery fragmented: Walmart 17.3% share. Online grocery only ~2% of US sales pre-deal. Post-deal catalysed Walmart–Jet, Target–Shipt, Kroger–Ocado responses.</p>' },
      { h: 'Target — Whole Foods', html: '<p>Premium organic positioning; 8 consecutive quarters of comp-store declines before deal. JANA activist stake (8.8%) pushed for sale. Revenue ~$15.7bn FY2016 across 456 stores. Higher cost base than mass-market grocers.</p>' },
      { h: 'Acquirer — Amazon', html: '<p>Three-layer platform: Retail, Prime, AWS (~25% margin cross-subsidises thin retail). Top prior deals: Zappos, Twitch. Needed physical nodes for grocery fulfilment and Prime Now expansion.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Amazon:</strong> 460+ urban stores as fulfilment/pickup; customer data; block competitors from WFM real estate</li><li><strong>Whole Foods:</strong> Exit for activists; scale vs Kroger/Costco organic push</li><li>Not primarily financial — scope / vertical integration</li></ul>' },
      { h: 'Deal structure', html: '<p>Announced Jun 2017. All-cash $42/share, ~$13.7bn EV. ~12.8× EV/EBITDA. Bridge loan + senior unsecured notes. No financing condition — Amazon had ~$26bn liquidity.</p>' },
      { h: 'Post-deal', html: '<p>Prime discounts at WFM, Amazon lockers, delivery integration. Sector-wide rush to build last-mile. Measured on strategic positioning succeeded; on near-term earnings less clear.</p>' },
    ],
    traps: ['Scope deal — revenue synergies speculative, not cost synergies', 'WFM &lt;4% of Amazon sales — option value framing', 'Activist (JANA) forced process', 'Triggered competitor omnichannel M&A wave'],
  },
  {
    id: 4,
    title: 'Facebook (Meta) — Instagram',
    year: 2012,
    value: '~$1.0bn announced (~$715m at close)',
    closed: 'Sep 2012',
    dealType: 'Friendly / bilateral',
    consideration: '$300m cash + 23M FB shares',
    premium: 'N/A (pre-revenue)',
    sector: 'Social / mobile',
    motive: 'Scope — mobile pivot + competitive pre-emption',
    summary: 'Zuckerberg closed Instagram in a weekend, 5 weeks before Facebook\'s $16bn IPO. 13 employees, 30M users, zero revenue — among the best M&A investments ever ($32bn+ annual ad revenue by 2024).',
    sections: [
      { h: 'Sector context', html: '<p>2012: smartphones &gt;1bn users; social shifting mobile-first. Winner-takes-most network effects. M&A wave: Google/Motorola $12.5bn, MS/Skype $8.5bn. High valuations on user growth, not earnings.</p>' },
      { h: 'Acquirer', html: '<p>845M MAU but critical <strong>mobile gap</strong>. Desktop-first. IPO narrative needed mobile credibility. Prior acqui-hires: Snaptu, Divvyshot.</p>' },
      { h: 'Target', html: '<p>13 employees, 30M+ iOS users, $0 revenue. Series B at $500M valuation weeks before deal. Android launch: 1M downloads first day (Apr 2012).</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Mobile pivot</strong> — instant mobile-native capability</li><li><strong>Competitive pre-emption</strong> — Twitter bid ~$525M</li><li><strong>IPO signalling</strong> — credible mobile story for investors</li><li><strong>Acqui-hire</strong> — $194M unvested retention over 3 years</li></ul>' },
      { h: 'Deal structure', html: '<p>$300M cash + 23M shares. Founders stayed 6 years. Separate brand preserved (deferred integration). FTC cleared 5-0 (Aug 2012); later antitrust suit (2020) — Meta prevailed 2025.</p>' },
      { h: 'Post-deal', html: '<p>30M → 3bn MAU. ~40% of Meta revenue from Instagram by mid-2020s. Citi standalone value $35bn (2018); BI estimate $100bn+. Founders departed 2018 — governance cost, not financial failure.</p>' },
    ],
    traps: ['Pre-revenue valuation — strategic optionality', 'Deferred integration preserved brand', 'Announced $1bn vs ~$715m at close (FB share price moved)', '5 weeks before IPO — timing not coincidental'],
  },
  {
    id: 5,
    title: 'Kraft — Cadbury',
    year: 2010,
    value: '$19.5bn',
    closed: 'Feb 2010',
    dealType: 'Hostile → friendly',
    consideration: 'Cash + Kraft shares',
    premium: '~50%',
    sector: 'Global confectionery',
    motive: 'Scale + emerging markets (India)',
    summary: 'Structurally inevitable after Mars–Wrigley ($23bn, 2008) left Cadbury as the only large independent confectioner. Strategically right direction, too expensive, poor post-merger integration — Mondelez spin-off within 2 years.',
    sections: [
      { h: 'Sector context', html: '<p>Global confectionery &gt;$150bn. High barriers to entry — brands take decades. Post-GFC valuations depressed. Mars–Wrigley closed alternatives; Cadbury was <strong>the only target</strong>.</p>' },
      { h: 'Acquirer — Kraft', html: '<p>~$40bn revenue; weak in confectionery vs Nestlé. Overexposed US/Western Europe; underexposed India/EM. Activist Nelson Peltz (Trian) pushed for transformative M&A. CEO Irene Rosenfeld.</p>' },
      { h: 'Target — Cadbury', html: '<p>Founded 1824; Quaker heritage / Bournville. Pure-play post-2008 demerger. #2 global confectioner. <strong>India: 70%+ share</strong> in some segments — key prize. Adams gum acquisition ($4.2bn, 2003) showed integration skill.</p>' },
      { h: '4-block framework', html: '<ul><li><strong>Timing:</strong> Post-crisis window + Mars–Wrigley closed the set</li><li><strong>Efficiency:</strong> $675M promised synergies (hard faster than revenue)</li><li><strong>Market position:</strong> Global snacks leader; India distribution</li><li><strong>Managers:</strong> Hubris / agency — Rosenfeld + Peltz pressure</li><li><strong>Opportunity:</strong> Last large independent confectioner</li></ul>' },
      { h: 'Deal process', html: '<p>Sept 2009 initial approach rejected. Nov 2009 hostile £9.8bn bid. Jan 2010 raised to £11.9bn ($19.5bn). Cadbury board accepted Feb 2010. UK Takeover Panel scrutiny.</p>' },
      { h: 'Post-deal', html: '<p><strong>Somerdale controversy:</strong> Kraft reversed promise to keep Bristol plant open — shifted UK takeover politics. Hard synergies beat plan; revenue synergies missed. Mondelez created 2012. Cadbury SH gained ~50%; Kraft SH short-term negative.</p>' },
    ],
    traps: ['Hostile → friendly — UK takeover rules & Somerdale', 'Hard synergies delivered, soft/revenue did not', 'Mondelez spin = admission of portfolio mismatch', 'India distribution was the real strategic prize', 'Hubris / overpayment — Kraft SH did not win'],
  },
  {
    id: 6,
    title: 'Disney — 21st Century Fox',
    year: 2019,
    value: '$71.3bn',
    closed: 'Mar 2019',
    dealType: 'Friendly (CEO-to-CEO)',
    consideration: 'Cash + stock election',
    premium: 'Varies by election',
    sector: 'Media & entertainment / streaming',
    motive: 'Scope — IP library + DTC scale',
    summary: 'Iger called Murdoch directly (late 2017). Disney acquired Fox studios, FX, Nat Geo, Star India, Hulu control — excluded Fox News/Broadcast (new Fox Corp). Driven by Netflix disruption and content arms race.',
    sections: [
      { h: 'Sector context', html: '<p>Netflix 33M→167M subs (2012–19). Cord-cutting hit ESPN. Content spend arms race. $200bn+ in mega-deals 2017–19: AT&T/TW $85bn, Disney/Fox $71.3bn, Comcast/Sky $40bn, CBS/Viacom $30bn.</p>' },
      { h: 'Acquirer — Disney', html: '<p>FY2018: Media Networks 41%, Parks 34%, Studio 17%. Prior playbook: ABC ($19bn), Pixar ($7.4bn), Marvel ($4bn), Lucasfilm ($4.05bn), BAMTech ($1.58bn). Bob Iger CEO.</p>' },
      { h: 'Target — Fox', html: '<p>FY2018 revenue $30.4bn. Filmed entertainment (Avatar, X-Men, Simpsons) 29%; cable networks 52%. <strong>Excluded:</strong> Fox Broadcasting, Fox News → Fox Corporation. Murdoch kept news/sports (not streamable).</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Disney:</strong> Disney+ content; Hulu 30%→60%; Star India 700M+ viewers; X-Men back to Marvel</li><li><strong>Fox:</strong> Sell at peak valuation; cannot match Netflix/Amazon content budgets; James vs Rupert Murdoch disagreement</li></ul>' },
      { h: 'Bidding war', html: '<p>Dec 2017: Disney $52.4bn all-stock. May 2018: Comcast $65bn all-cash counter. Jun 2018: Disney $71.3bn cash+stock; Comcast withdrew. Shareholders approved Jul 2018.</p>' },
      { h: 'Structure', html: '<p>Shareholders elected $38 cash or 0.4517 DIS shares. 51% chose cash (oversubscribed). Final price $51.57/share at close (based on DIS avg price, not fixed at signing).</p>' },
      { h: 'Post-deal', html: '<p>Disney+ launched Nov 2019. Hulu majority control. Integration of 21CF assets into DTC strategy. Scale economics spread content spend.</p>' },
    ],
    traps: ['Murdoch kept Fox News/Sports — carve-out not full sale', 'Comcast counterbid forced cash component', 'Cash election oversubscribed — financing risk', 'IP scarcity thesis — content libraries as strategic assets'],
  },
  {
    id: 7,
    title: 'Marriott — Starwood',
    year: 2016,
    value: '~$13.6bn',
    closed: 'Sep 2016',
    dealType: 'Friendly (competitive process)',
    consideration: '0.80 MAR shares + $21 cash per HOT share',
    premium: 'Raised after Anbang bid',
    sector: 'Global hospitality',
    motive: 'Scale + loyalty + OTA leverage',
    summary: 'Largest hotel merger ever: 5,700 properties, 1.1M rooms. Starwood ran strategic review (Lazard, Apr 2015); Anbang counterbid Mar 2016 forced Marriott to raise offer. Closed Sep 2016.',
    sections: [
      { h: 'Sector context', html: '<p>OTAs (Expedia, Booking) charge 15–25% commissions. Airbnb ~$25.5bn valuation pressured incumbents. Asset-light model: fee revenue from franchise/management, not real estate ownership.</p>' },
      { h: 'Acquirer — Marriott', html: '<p>Since 1927; asset-light since 1993 split from Host Marriott. FY2015 revenue ~$14.5bn; ROIC 49.2%. 19 brands; Marriott Rewards 55M members. Strong North America, weaker internationally.</p>' },
      { h: 'Target — Starwood', html: '<p>1,297 properties, 100 countries. SPG loyalty: 50% of room nights. Revenue declining ($6.1bn→$5.8bn 2013–15). CEO instability; activist pressure. Asset-light pivot since 2006.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Scale:</strong> #1 globally; bargaining power vs OTAs</li><li><strong>Loyalty:</strong> ~75M combined members (54M MR + 21M SPG)</li><li><strong>Geography:</strong> Starwood stronger internationally & luxury (W, St. Regis, Westin)</li><li><strong>Cost synergies:</strong> $200M→$250M/yr (reservations, purchasing, HQ)</li></ul>' },
      { h: 'Deal process', html: '<p>Signed Nov 2015. Mar 2016: Anbang consortium counterbid → Marriott raised to 0.80 shares + $21 cash. Apr 2016 shareholder approval. Sep 2016 close. Anbang later acquired Strategic Hotels $6.5bn.</p>' },
      { h: 'Post-deal', html: '<p>SPG merged into Marriott Bonvoy (2018). Combined platform vs Airbnb and OTAs. Integration complexity across 30 brands.</p>' },
    ],
    traps: ['Anbang counterbid — Chinese capital in hospitality 2015–16', 'SPG was core asset — loyalty moat', 'Starwood seller weakness (declining revenue, activists)', 'Asset-light — synergies in G&A/systems not property'],
  },
  {
    id: 8,
    title: 'Volkswagen — Porsche',
    year: '2009–2012',
    value: 'Porsche AG ~€8.36bn paid',
    closed: 'Aug 2012 (VW absorbs Porsche AG)',
    dealType: 'Reverse takeover / family saga',
    consideration: 'Cash (VW buys remaining Porsche AG)',
    premium: 'N/A — inverted control',
    sector: 'Automotive',
    motive: 'Scale + platform sharing (forced)',
    summary: 'Porsche tried to acquire VW via cash-settled options (built 74.1% effective stake Oct 2008) but €14bn options debt + GFC forced reversal. VW lent Porsche €700m (Mar 2009), then absorbed Porsche AG (2012). Porsche SE still holds 50.7% of VW voting shares.',
    sections: [
      { h: 'Sector context', html: '<p>Multi-brand groups dominate: scale amortises platform R&D (€billions per architecture). Porsche RoE ~22.8% vs VW ~3.0% (2005) — asymmetry drove options strategy. Cayenne shared VW platform (~30% components from VW).</p>' },
      { h: 'The paradox', html: '<ol><li>Porsche built &gt;50% VW stake via options — bidder became target</li><li>GFC froze credit; Porsche net income −83% H1 2009</li><li>VW €700m rescue loan Mar 2009 — power flipped</li><li>Porsche-Piëch family controls both via Porsche SE</li></ol>' },
      { h: 'Family dynamics', html: '<p>Ferdinand Porsche designed VW Beetle (1934). "Kampf der Egos": Wolfgang Porsche (Porsche AG chair) vs Ferdinand Piëch (VW chair until 2015). Oct 2008 short squeeze: Porsche disclosure briefly made VW world\'s most valuable company.</p>' },
      { h: 'Deal outcome', html: '<p>VW absorbed Porsche AG operating business (Aug 2012). Porsche SE remains holding company with majority VW voting rights. Carrying value &gt;€27bn vs ~€8.36bn paid — accounting vs cash flow distinction.</p>' },
      { h: 'Strategic logic', html: '<p>Inevitable combination; crisis decided <em>who buys whom</em>. Platform sharing (Touareg/Q7/Cayenne), R&D scale, electrification pressure. 2022 Porsche AG IPO at ~€75bn valuation.</p>' },
    ],
    traps: ['Reverse takeover — not a normal friendly merger', 'Cash-settled options created hidden leverage', 'Family control persists via Porsche SE', 'Porsche RoE vs VW RoE explains bidding aggression', 'Oct 2008 VW short squeeze — famous market event'],
  },
  {
    id: 9,
    title: 'LVMH — Tiffany',
    year: 2021,
    value: '$15.8bn',
    closed: 'Jan 2021',
    dealType: 'Friendly (with litigation)',
    consideration: 'All-cash ($131.50/share final)',
    premium: '34.2% over undisturbed ($98)',
    sector: 'Luxury jewellery',
    motive: 'Scope — hard luxury / US bridal',
    summary: 'Largest luxury deal ever. LVMH strengthened Watches & Jewellery division (8% of group vs 44% Fashion). Pandemic dispute: LVMH tried to withdraw Sep 2020; renegotiated from $135 to $131.50; closed Jan 2021.',
    sections: [
      { h: 'Sector context', html: '<p>Luxury market €281bn (2019) → −23% (2020) → €363bn (2024). Consolidation: Richemont/YNAP, Capri/Versace, Moncler/Stone Island. LVMH #1 at €84.7bn revenue (2024).</p>' },
      { h: 'Acquirer — LVMH', html: '<p>Founded 1987 (LV + Moët Hennessy). 70+ maisons. Prior deals: TAG Heuer, Fendi, Bulgari (€3.7bn, 2011). Bernard Arnault. Jewellery division underperforming vs Richemont (Cartier).</p>' },
      { h: 'Target — Tiffany', html: '<p>Founded 1837; iconic Blue Box / bridal. ~300 stores; US-heavy (Europe only 11% revenue). Like-for-like sales −4% (2017) — millennial relevance slipping. CEO Alessandro Bogliolo "Next Generation" transformation plan needed capital.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>LVMH:</strong> Close gap with Richemont; US bridal dominance; buy at ~30% discount to peak</li><li><strong>Tiffany:</strong> Fund transformation; Asia expansion via LVMH network; certainty in trade-war uncertainty</li></ul>' },
      { h: 'Deal process', html: '<p>Oct 2019: LVMH $120/share — rejected. Nov 2019: signed $135 (+37%). Mar 2020: COVID. Sep 2020: LVMH withdrawal attempt + Tiffany lawsuit. Oct 2020: renegotiated $131.50. Jan 2021: close.</p>' },
      { h: 'Valuation', html: '<p>Peer median implied ~$8.2bn standalone vs $15.8bn paid. Gap = control + strategic + synergy premia. Financed: €10bn bonds + €5bn cash. EV/EBITDA ~19× vs peer median ~12×.</p>' },
      { h: 'Post-deal', html: '<p>Tiffany record revenue 2021. Watches & Jewellery operating profit doubled. LVMH applied Bulgari playbook to globalise jewellery house.</p>' },
    ],
    traps: ['MAC clause / pandemic litigation — renegotiation not walk-away', 'All-cash despite bond financing', 'Trophy asset — strategic premium over DCF', 'Bulgari 2011 as integration template', '$120 → $135 → $131.50 price path'],
  },
];

const COMPARE_ROWS = [
  { deal: 'Microsoft–LinkedIn', year: '2016', value: '$26.2bn', type: 'Friendly auction', pay: 'All-cash', premium: '49.5%', motive: 'Scope (data/cloud)', outcome: 'Success — federated integration' },
  { deal: 'CaixaBank–Bankia', year: '2020–21', value: '€4.3bn eq.', type: 'Merger absorption', pay: 'All-share', premium: '20%', motive: 'Scale (domestic bank)', outcome: 'Ongoing integration' },
  { deal: 'Amazon–Whole Foods', year: '2017', value: '$13.7bn', type: 'Friendly', pay: 'All-cash', premium: '~27%', motive: 'Scope (omnichannel)', outcome: 'Strategic win; sector catalyst' },
  { deal: 'Facebook–Instagram', year: '2012', value: '~$1bn', type: 'Bilateral', pay: 'Cash + stock', premium: 'N/A', motive: 'Scope (mobile)', outcome: 'Exceptional — $32bn+ rev' },
  { deal: 'Kraft–Cadbury', year: '2010', value: '$19.5bn', type: 'Hostile→friendly', pay: 'Cash + stock', premium: '~50%', motive: 'Scale + India EM', outcome: 'Mixed — Mondelez spin' },
  { deal: 'Disney–Fox', year: '2019', value: '$71.3bn', type: 'Friendly', pay: 'Cash + stock', premium: 'Varies', motive: 'Scope (IP/streaming)', outcome: 'Disney+ acceleration' },
  { deal: 'Marriott–Starwood', year: '2016', value: '~$13.6bn', type: 'Friendly (+Anbang)', pay: 'Stock + cash', premium: 'Raised', motive: 'Scale + loyalty', outcome: 'Largest hotel co.' },
  { deal: 'VW–Porsche', year: '2009–12', value: '€8.36bn', type: 'Reverse takeover', pay: 'Cash', premium: 'N/A', motive: 'Scale (forced)', outcome: 'Family still controls VW' },
  { deal: 'LVMH–Tiffany', year: '2021', value: '$15.8bn', type: 'Friendly + suit', pay: 'All-cash', premium: '34.2%', motive: 'Scope (jewellery)', outcome: 'Record Tiffany 2021' },
];

const EXAM_FRAMEWORK = [
  { topic: 'Scale vs scope', formula: 'Scale = cost synergies, market share · Scope = new capabilities, geography, IP' },
  { topic: '4-block motives (Kraft)', formula: 'Timing · Efficiency/synergies · Market position · Managers/opportunity' },
  { topic: 'Premium drivers', formula: 'Control + strategic + synergy premia − distress discount' },
  { topic: 'Consideration types', formula: 'Cash (certainty) vs stock (risk sharing) vs mixed' },
  { topic: 'Friendly vs hostile', formula: 'Board support · UK Takeover Code · termination fees' },
  { topic: 'Hard vs soft synergies', formula: 'Hard = cost (faster) · Soft = revenue/culture (slower, riskier)' },
  { topic: 'Badwill', formula: 'Target BV > price → negative goodwill (banks)' },
  { topic: 'MAC clause', formula: 'Material Adverse Change — renegotiate or litigate (Tiffany)' },
];
