const DEAL_LABELS = {
  1: 'Microsoft–LinkedIn',
  2: 'CaixaBank–Bankia',
  3: 'Amazon–Whole Foods',
  4: 'Facebook–Instagram',
  5: 'Kraft–Cadbury',
  6: 'Disney–21st Century Fox',
  7: 'Marriott–Starwood',
  8: 'VW–Porsche',
  9: 'LVMH–Tiffany',
};

const STUDY_DEALS = [
  {
    id: 1,
    title: 'Microsoft  -  LinkedIn',
    year: 2016,
    value: '$26.2bn',
    closed: 'Dec 2016',
    dealType: 'Friendly auction',
    consideration: 'All-cash ($196/share)',
    premium: '49.5%',
    sector: 'Tech / SaaS / professional data',
    motive: 'Scope  -  data, cloud, CRM',
    summary: 'Microsoft\'s largest acquisition: all-cash purchase of LinkedIn at $196/share (49.5% premium), financed by ~$20bn bond issuance to avoid repatriating offshore cash. Scope deal for professional identity data, Dynamics 365 integration, and blocking Salesforce.',
    sections: [
      { h: 'Sector context', html: '<p>2016 tech M&A hit ~$467bn driven by <strong>cloud shift</strong>, <strong>data as asset</strong>, and <strong>scope over scale</strong>. Largest pure-software deal of the year; comparable to Oracle–NetSuite, SoftBank–ARM.</p>' },
      { h: 'Acquirer', html: '<p>Nadella\'s "cloud-first" pivot after Nokia ($7.2bn) and aQuantive ($6.2bn write-down) failures. Prior wins: Skype → Teams foundation, Mojang. Held &gt;$100bn offshore cash.</p>' },
      { h: 'Target', html: '<p>433M members; Talent Solutions 65% of revenue. 13 years of structured professional data ("Economic Graph"). Net margin −5.5% in 2015  -  structurally unprofitable standalone.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Microsoft:</strong> Identity-aware ecosystem; Office/Teams/Dynamics + LinkedIn data; block Salesforce</li><li><strong>LinkedIn:</strong> Azure migration cuts capex; enterprise distribution via MS sales force; federated autonomy (Weiner stayed CEO)</li></ul>' },
      { h: 'Deal process', html: '<p>Nadella approached Weiner Feb 2016. Bidders: Microsoft, Salesforce, Google, Party C. Facebook withdrew. Best-and-final: MS <strong>$196 all-cash</strong> vs Salesforce <strong>$186 cash+stock</strong>. All-cash won  -  no exchange-ratio risk, no financing condition.</p>' },
      { h: 'Valuation', html: '<p>EV/Revenue 8.76× (FY2015 $2,991M rev); EV/EBITDA 33.6×. $10bn bidding premium vs standalone ~$16.2bn. Termination fees: $725M each side (symmetric  -  MS absorbed EC risk).</p>' },
      { h: 'Post-deal', html: '<p>Members 500M→825M by 2020. Synergies: Sales Navigator + Dynamics (12–15% productivity), Azure migration ($150M run-rate by 2018). Federated integration  -  opposite of Nokia failure. Shares −3% on announcement.</p>' },
    ],
    traps: ['All-cash vs Salesforce stock mix  -  structure mattered as much as price', 'Scope deal (capabilities/data), not cost-cutting', '$20bn bonds at ~2% vs 35% repatriation tax', 'Nokia lesson → kept LinkedIn brand & CEO autonomy'],
  },
  {
    id: 2,
    title: 'CaixaBank  -  Bankia',
    year: '2020–21',
    value: '~€4.3bn equity',
    closed: 'Mar 2021',
    dealType: 'Friendly merger by absorption',
    consideration: 'All-share (0.6845 CBK per Bankia share)',
    premium: '20% over unaffected ratio',
    sector: 'Spanish retail banking',
    motive: 'Scale + cost synergies',
    summary: 'All-share domestic banking merger creating Spain\'s largest bank (~€660bn assets, 20M+ customers). Driven by negative rates, branch overcapacity, COVID provisions, and ECB support for consolidation.',
    sections: [
      { h: 'Sector context', html: '<p>Spanish banks under structural pressure: ECB negative deposit rate compressed NIM; branches fell 45,662 (2008) → 23,340 (2020). H1 2020: €26.5bn provisions, sector loss €11.5bn. Domestic consolidation extracts branch/IT synergies better than cross-border.</p>' },
      { h: 'Acquirer  -  CaixaBank', html: '<p>Listed successor to "la Caixa". Strong retail, bancassurance, asset management. Prior M&A: Banca Cívica (2012), Banco de Valencia (2013), Barclays Spain (2014), BPI Portugal (2017).</p>' },
      { h: 'Target  -  Bankia', html: '<p>Formed 2010 from merger of seven savings banks. Nationalised 2012 after €22.4bn bailout. State (FROB) held ~61.8% at deal  -  <strong>state exit set the clock</strong>. Distressed but large deposit franchise.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>CaixaBank:</strong> Scale first (defend ROE), scope second (fee income cross-sell), regulatory power as by-product</li><li><strong>Bankia:</strong> Friendly cover for distressed fundamentals; state exit</li><li><strong>Deal type:</strong> In-market merger  -  overlapping branches, IT, admin</li></ul>' },
      { h: 'Structure & valuation', html: '<p>CaixaBank absorbs Bankia. Exchange ratio 0.6845 new CBK shares per Bankia share. Combined: #1 Spain by domestic assets, ~€368bn loan book. ECB guide (Jan 2021): integration plans not auto-penalised; badwill profits strengthen capital.</p>' },
      { h: 'Post-deal', html: '<p>Cost synergies from branch closures and platform integration. Comparable wave: Intesa/UBI (Italy), Unicaja/Liberbank (Spain). BBVA–Sabadell explored but abandoned.</p>' },
    ],
    traps: ['All-share, not cash  -  no liquidity event for Bankia holders beyond premium in ratio', 'Badwill / negative goodwill possible when buying below book', 'State seller (FROB)  -  political timing mattered', 'COVID accelerated consolidation logic'],
  },
  {
    id: 3,
    title: 'Amazon  -  Whole Foods',
    year: 2017,
    value: '$13.7bn',
    closed: 'Aug 2017',
    dealType: 'Friendly / negotiated',
    consideration: 'All-cash ($42/share)',
    premium: '~27%',
    sector: 'US grocery / omnichannel retail',
    motive: 'Scope  -  physical grocery footprint',
    summary: 'Amazon\'s entry into physical grocery: $13.7bn all-cash for 456 stores. Strategic option on omnichannel and last-mile  -  WFM was &lt;4% of Amazon revenue; deal bought infrastructure, not earnings.',
    sections: [
      { h: 'Sector context', html: '<p>US grocery fragmented: Walmart 17.3% share. Online grocery only ~2% of US sales pre-deal. Post-deal catalysed Walmart–Jet, Target–Shipt, Kroger–Ocado responses.</p>' },
      { h: 'Target  -  Whole Foods', html: '<p>Premium organic positioning; 8 consecutive quarters of comp-store declines before deal. JANA activist stake (8.8%) pushed for sale. Revenue ~$15.7bn FY2016 across 456 stores. Higher cost base than mass-market grocers.</p>' },
      { h: 'Acquirer  -  Amazon', html: '<p>Three-layer platform: Retail, Prime, AWS (~25% margin cross-subsidises thin retail). Top prior deals: Zappos, Twitch. Needed physical nodes for grocery fulfilment and Prime Now expansion.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Amazon:</strong> 460+ urban stores as fulfilment/pickup; customer data; block competitors from WFM real estate</li><li><strong>Whole Foods:</strong> Exit for activists; scale vs Kroger/Costco organic push</li><li>Not primarily financial  -  scope / vertical integration</li></ul>' },
      { h: 'Deal structure', html: '<p>Announced Jun 2017. All-cash $42/share, ~$13.7bn EV. ~12.8× EV/EBITDA. Bridge loan + senior unsecured notes. No financing condition  -  Amazon had ~$26bn liquidity.</p>' },
      { h: 'Post-deal', html: '<p>Prime discounts at WFM, Amazon lockers, delivery integration. Sector-wide rush to build last-mile. Measured on strategic positioning succeeded; on near-term earnings less clear.</p>' },
    ],
    traps: ['Scope deal  -  revenue synergies speculative, not cost synergies', 'WFM &lt;4% of Amazon sales  -  option value framing', 'Activist (JANA) forced process', 'Triggered competitor omnichannel M&A wave'],
  },
  {
    id: 4,
    title: 'Facebook (Meta)  -  Instagram',
    year: 2012,
    value: '~$1.0bn announced (~$715m at close)',
    closed: 'Sep 2012',
    dealType: 'Friendly / bilateral',
    consideration: '$300m cash + 23M FB shares',
    premium: 'N/A (pre-revenue)',
    sector: 'Social / mobile',
    motive: 'Scope  -  mobile pivot + competitive pre-emption',
    summary: 'Zuckerberg closed Instagram in a weekend, 5 weeks before Facebook\'s $16bn IPO. 13 employees, 30M users, zero revenue  -  among the best M&A investments ever ($32bn+ annual ad revenue by 2024).',
    sections: [
      { h: 'Sector context', html: '<p>2012: smartphones &gt;1bn users; social shifting mobile-first. Winner-takes-most network effects. M&A wave: Google/Motorola $12.5bn, MS/Skype $8.5bn. High valuations on user growth, not earnings.</p>' },
      { h: 'Acquirer', html: '<p>845M MAU but critical <strong>mobile gap</strong>. Desktop-first. IPO narrative needed mobile credibility. Prior acqui-hires: Snaptu, Divvyshot.</p>' },
      { h: 'Target', html: '<p>13 employees, 30M+ iOS users, $0 revenue. Series B at $500M valuation weeks before deal. Android launch: 1M downloads first day (Apr 2012).</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Mobile pivot</strong>  -  instant mobile-native capability</li><li><strong>Competitive pre-emption</strong>  -  Twitter bid ~$525M</li><li><strong>IPO signalling</strong>  -  credible mobile story for investors</li><li><strong>Acqui-hire</strong>  -  $194M unvested retention over 3 years</li></ul>' },
      { h: 'Deal structure', html: '<p>$300M cash + 23M shares. Founders stayed 6 years. Separate brand preserved (deferred integration). FTC cleared 5-0 (Aug 2012); later antitrust suit (2020)  -  Meta prevailed 2025.</p>' },
      { h: 'Post-deal', html: '<p>30M → 3bn MAU. ~40% of Meta revenue from Instagram by mid-2020s. Citi standalone value $35bn (2018); BI estimate $100bn+. Founders departed 2018  -  governance cost, not financial failure.</p>' },
    ],
    traps: ['Pre-revenue valuation  -  strategic optionality', 'Deferred integration preserved brand', 'Announced $1bn vs ~$715m at close (FB share price moved)', '5 weeks before IPO  -  timing not coincidental'],
  },
  {
    id: 5,
    title: 'Kraft  -  Cadbury',
    year: 2010,
    value: '$19.5bn',
    closed: 'Feb 2010',
    dealType: 'Hostile → friendly',
    consideration: 'Cash + Kraft shares',
    premium: '~50%',
    sector: 'Global confectionery',
    motive: 'Scale + emerging markets (India)',
    summary: 'Structurally inevitable after Mars–Wrigley ($23bn, 2008) left Cadbury as the only large independent confectioner. Strategically right direction, too expensive, poor post-merger integration  -  Mondelez spin-off within 2 years.',
    sections: [
      { h: 'Sector context', html: '<p>Global confectionery &gt;$150bn. High barriers to entry  -  brands take decades. Post-GFC valuations depressed. Mars–Wrigley closed alternatives; Cadbury was <strong>the only target</strong>.</p>' },
      { h: 'Acquirer  -  Kraft', html: '<p>~$40bn revenue; weak in confectionery vs Nestlé. Overexposed US/Western Europe; underexposed India/EM. Activist Nelson Peltz (Trian) pushed for transformative M&A. CEO Irene Rosenfeld.</p>' },
      { h: 'Target  -  Cadbury', html: '<p>Founded 1824; Quaker heritage / Bournville. Pure-play post-2008 demerger. #2 global confectioner. <strong>India: 70%+ share</strong> in some segments  -  key prize. Adams gum acquisition ($4.2bn, 2003) showed integration skill.</p>' },
      { h: '4-block framework', html: '<ul><li><strong>Timing:</strong> Post-crisis window + Mars–Wrigley closed the set</li><li><strong>Efficiency:</strong> $675M promised synergies (hard faster than revenue)</li><li><strong>Market position:</strong> Global snacks leader; India distribution</li><li><strong>Managers:</strong> Hubris / agency  -  Rosenfeld + Peltz pressure</li><li><strong>Opportunity:</strong> Last large independent confectioner</li></ul>' },
      { h: 'Deal process', html: '<p>Sept 2009 initial approach rejected. Nov 2009 hostile £9.8bn bid. Jan 2010 raised to £11.9bn ($19.5bn). Cadbury board accepted Feb 2010. UK Takeover Panel scrutiny.</p>' },
      { h: 'Post-deal', html: '<p><strong>Somerdale controversy:</strong> Kraft reversed promise to keep Bristol plant open  -  shifted UK takeover politics. Hard synergies beat plan; revenue synergies missed. Mondelez created 2012. Cadbury SH gained ~50%; Kraft SH short-term negative.</p>' },
    ],
    traps: ['Hostile → friendly  -  UK takeover rules & Somerdale', 'Hard synergies delivered, soft/revenue did not', 'Mondelez spin = admission of portfolio mismatch', 'India distribution was the real strategic prize', 'Hubris / overpayment  -  Kraft SH did not win'],
  },
  {
    id: 6,
    title: 'Disney  -  21st Century Fox',
    year: 2019,
    value: '$71.3bn',
    closed: 'Mar 2019',
    dealType: 'Friendly (CEO-to-CEO)',
    consideration: 'Cash + stock election',
    premium: 'Varies by election',
    sector: 'Media & entertainment / streaming',
    motive: 'Scope  -  IP library + DTC scale',
    summary: 'Iger called Murdoch directly (late 2017). Disney acquired Fox studios, FX, Nat Geo, Star India, Hulu control  -  excluded Fox News/Broadcast (new Fox Corp). Driven by Netflix disruption and content arms race.',
    sections: [
      { h: 'Sector context', html: '<p>Netflix 33M→167M subs (2012–19). Cord-cutting hit ESPN. Content spend arms race. $200bn+ in mega-deals 2017–19: AT&T/TW $85bn, Disney/Fox $71.3bn, Comcast/Sky $40bn, CBS/Viacom $30bn.</p>' },
      { h: 'Acquirer  -  Disney', html: '<p>FY2018: Media Networks 41%, Parks 34%, Studio 17%. Prior playbook: ABC ($19bn), Pixar ($7.4bn), Marvel ($4bn), Lucasfilm ($4.05bn), BAMTech ($1.58bn). Bob Iger CEO.</p>' },
      { h: 'Target  -  Fox', html: '<p>FY2018 revenue $30.4bn. Filmed entertainment (Avatar, X-Men, Simpsons) 29%; cable networks 52%. <strong>Excluded:</strong> Fox Broadcasting, Fox News → Fox Corporation. Murdoch kept news/sports (not streamable).</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Disney:</strong> Disney+ content; Hulu 30%→60%; Star India 700M+ viewers; X-Men back to Marvel</li><li><strong>Fox:</strong> Sell at peak valuation; cannot match Netflix/Amazon content budgets; James vs Rupert Murdoch disagreement</li></ul>' },
      { h: 'Bidding war', html: '<p>Dec 2017: Disney $52.4bn all-stock. May 2018: Comcast $65bn all-cash counter. Jun 2018: Disney $71.3bn cash+stock; Comcast withdrew. Shareholders approved Jul 2018.</p>' },
      { h: 'Structure', html: '<p>Shareholders elected $38 cash or 0.4517 DIS shares. 51% chose cash (oversubscribed). Final price $51.57/share at close (based on DIS avg price, not fixed at signing).</p>' },
      { h: 'Post-deal', html: '<p>Disney+ launched Nov 2019. Hulu majority control. Integration of 21CF assets into DTC strategy. Scale economics spread content spend.</p>' },
    ],
    traps: ['Murdoch kept Fox News/Sports  -  carve-out not full sale', 'Comcast counterbid forced cash component', 'Cash election oversubscribed  -  financing risk', 'IP scarcity thesis  -  content libraries as strategic assets'],
  },
  {
    id: 7,
    title: 'Marriott  -  Starwood',
    year: 2016,
    value: '~$13.6bn',
    closed: 'Sep 2016',
    dealType: 'Friendly (competitive process)',
    consideration: '0.80 MAR shares + $21 cash per HOT share',
    premium: 'Raised after Anbang bid',
    sector: 'Global hospitality',
    motive: 'Scale + loyalty + OTA leverage',
    summary: 'Largest hotel merger ever: 5,700 properties, 1.1M rooms. Starwood ran strategic review (Lazard, Apr 2015); Anbang counterbid Mar 2016 forced Marriott to raise offer. Closed Sep 2016.',
    sections: [
      { h: 'Sector context', html: '<p>OTAs (Expedia, Booking) charge 15–25% commissions. Airbnb ~$25.5bn valuation pressured incumbents. Asset-light model: fee revenue from franchise/management, not real estate ownership.</p>' },
      { h: 'Acquirer  -  Marriott', html: '<p>Since 1927; asset-light since 1993 split from Host Marriott. FY2015 revenue ~$14.5bn; ROIC 49.2%. 19 brands; Marriott Rewards 55M members. Strong North America, weaker internationally.</p>' },
      { h: 'Target  -  Starwood', html: '<p>1,297 properties, 100 countries. SPG loyalty: 50% of room nights. Revenue declining ($6.1bn→$5.8bn 2013–15). CEO instability; activist pressure. Asset-light pivot since 2006.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>Scale:</strong> #1 globally; bargaining power vs OTAs</li><li><strong>Loyalty:</strong> ~75M combined members (54M MR + 21M SPG)</li><li><strong>Geography:</strong> Starwood stronger internationally & luxury (W, St. Regis, Westin)</li><li><strong>Cost synergies:</strong> $200M→$250M/yr (reservations, purchasing, HQ)</li></ul>' },
      { h: 'Deal process', html: '<p>Signed Nov 2015. Mar 2016: Anbang consortium counterbid → Marriott raised to 0.80 shares + $21 cash. Apr 2016 shareholder approval. Sep 2016 close. Anbang later acquired Strategic Hotels $6.5bn.</p>' },
      { h: 'Post-deal', html: '<p>SPG merged into Marriott Bonvoy (2018). Combined platform vs Airbnb and OTAs. Integration complexity across 30 brands.</p>' },
    ],
    traps: ['Anbang counterbid  -  Chinese capital in hospitality 2015–16', 'SPG was core asset  -  loyalty moat', 'Starwood seller weakness (declining revenue, activists)', 'Asset-light  -  synergies in G&A/systems not property'],
  },
  {
    id: 8,
    title: 'Volkswagen  -  Porsche',
    year: '2009–2012',
    value: 'Porsche AG ~€8.36bn paid',
    closed: 'Aug 2012 (VW absorbs Porsche AG)',
    dealType: 'Reverse takeover / family saga',
    consideration: 'Cash (VW buys remaining Porsche AG)',
    premium: 'N/A  -  inverted control',
    sector: 'Automotive',
    motive: 'Scale + platform sharing (forced)',
    summary: 'Porsche tried to acquire VW via cash-settled options (built 74.1% effective stake Oct 2008) but €14bn options debt + GFC forced reversal. VW lent Porsche €700m (Mar 2009), then absorbed Porsche AG (2012). Porsche SE still holds 50.7% of VW voting shares.',
    sections: [
      { h: 'Sector context', html: '<p>Multi-brand groups dominate: scale amortises platform R&D (€billions per architecture). Porsche RoE ~22.8% vs VW ~3.0% (2005)  -  asymmetry drove options strategy. Cayenne shared VW platform (~30% components from VW).</p>' },
      { h: 'The paradox', html: '<ol><li>Porsche built &gt;50% VW stake via options  -  bidder became target</li><li>GFC froze credit; Porsche net income −83% H1 2009</li><li>VW €700m rescue loan Mar 2009  -  power flipped</li><li>Porsche-Piëch family controls both via Porsche SE</li></ol>' },
      { h: 'Family dynamics', html: '<p>Ferdinand Porsche designed VW Beetle (1934). "Kampf der Egos": Wolfgang Porsche (Porsche AG chair) vs Ferdinand Piëch (VW chair until 2015). Oct 2008 short squeeze: Porsche disclosure briefly made VW world\'s most valuable company.</p>' },
      { h: 'Deal outcome', html: '<p>VW absorbed Porsche AG operating business (Aug 2012). Porsche SE remains holding company with majority VW voting rights. Carrying value &gt;€27bn vs ~€8.36bn paid  -  accounting vs cash flow distinction.</p>' },
      { h: 'Strategic logic', html: '<p>Inevitable combination; crisis decided <em>who buys whom</em>. Platform sharing (Touareg/Q7/Cayenne), R&D scale, electrification pressure. 2022 Porsche AG IPO at ~€75bn valuation.</p>' },
    ],
    traps: ['Reverse takeover  -  not a normal friendly merger', 'Cash-settled options created hidden leverage', 'Family control persists via Porsche SE', 'Porsche RoE vs VW RoE explains bidding aggression', 'Oct 2008 VW short squeeze  -  famous market event'],
  },
  {
    id: 9,
    title: 'LVMH  -  Tiffany',
    year: 2021,
    value: '$15.8bn',
    closed: 'Jan 2021',
    dealType: 'Friendly (with litigation)',
    consideration: 'All-cash ($131.50/share final)',
    premium: '34.2% over undisturbed ($98)',
    sector: 'Luxury jewellery',
    motive: 'Scope  -  hard luxury / US bridal',
    summary: 'Largest luxury deal ever. LVMH strengthened Watches & Jewellery division (8% of group vs 44% Fashion). Pandemic dispute: LVMH tried to withdraw Sep 2020; renegotiated from $135 to $131.50; closed Jan 2021.',
    sections: [
      { h: 'Sector context', html: '<p>Luxury market €281bn (2019) → −23% (2020) → €363bn (2024). Consolidation: Richemont/YNAP, Capri/Versace, Moncler/Stone Island. LVMH #1 at €84.7bn revenue (2024).</p>' },
      { h: 'Acquirer  -  LVMH', html: '<p>Founded 1987 (LV + Moët Hennessy). 70+ maisons. Prior deals: TAG Heuer, Fendi, Bulgari (€3.7bn, 2011). Bernard Arnault. Jewellery division underperforming vs Richemont (Cartier).</p>' },
      { h: 'Target  -  Tiffany', html: '<p>Founded 1837; iconic Blue Box / bridal. ~300 stores; US-heavy (Europe only 11% revenue). Like-for-like sales −4% (2017)  -  millennial relevance slipping. CEO Alessandro Bogliolo "Next Generation" transformation plan needed capital.</p>' },
      { h: 'Strategic rationale', html: '<ul><li><strong>LVMH:</strong> Close gap with Richemont; US bridal dominance; buy at ~30% discount to peak</li><li><strong>Tiffany:</strong> Fund transformation; Asia expansion via LVMH network; certainty in trade-war uncertainty</li></ul>' },
      { h: 'Deal process', html: '<p>Oct 2019: LVMH $120/share  -  rejected. Nov 2019: signed $135 (+37%). Mar 2020: COVID. Sep 2020: LVMH withdrawal attempt + Tiffany lawsuit. Oct 2020: renegotiated $131.50. Jan 2021: close.</p>' },
      { h: 'Valuation', html: '<p>Peer median implied ~$8.2bn standalone vs $15.8bn paid. Gap = control + strategic + synergy premia. Financed: €10bn bonds + €5bn cash. EV/EBITDA ~19× vs peer median ~12×.</p>' },
      { h: 'Post-deal', html: '<p>Tiffany record revenue 2021. Watches & Jewellery operating profit doubled. LVMH applied Bulgari playbook to globalise jewellery house.</p>' },
    ],
    traps: ['MAC clause / pandemic litigation  -  renegotiation not walk-away', 'All-cash despite bond financing', 'Trophy asset  -  strategic premium over DCF', 'Bulgari 2011 as integration template', '$120 → $135 → $131.50 price path'],
  },
];

const COMPARE_ROWS = [
  {
    deal: 'Microsoft · LinkedIn', year: '2016', yearSort: 2016, value: '$26.2bn', valueSort: 26.2,
    type: 'Friendly auction', pay: 'All-cash', premium: '49.5%', premiumSort: 49.5,
    motive: 'Scope (data/cloud)', outcome: 'Federated integration; Dynamics/Azure synergies',
    successAcquirer: 'Strong', successAcquirerScore: 4,
    successAcquirerNote: 'Scope delivered: federated integration, member growth, cloud migration. Premium was high but all-cash structure beat Salesforce.',
    successAcquiree: 'Strong', successAcquireeScore: 4,
    successAcquireeNote: 'Target SH: 49.5% all-cash premium; Weiner stayed CEO; brand autonomy preserved.',
    success: 'Strong', successScore: 4,
    successNote: 'Scope delivered: federated integration, member growth, cloud migration. Premium was high but all-cash structure beat Salesforce.',
  },
  {
    deal: 'CaixaBank · Bankia', year: '2020-21', yearSort: 2020, value: '€4.3bn eq.', valueSort: 4.3,
    type: 'Merger absorption', pay: 'All-share', premium: '20%', premiumSort: 20,
    motive: 'Scale (domestic bank)', outcome: 'Spain #1 bank; branch/IT synergies underway',
    successAcquirer: 'Moderate', successAcquirerScore: 3,
    successAcquirerNote: 'Scale logic sound; #1 domestic bank. Integration ongoing; badwill possible; too early for a clean win verdict.',
    successAcquiree: 'Moderate', successAcquireeScore: 3,
    successAcquireeNote: 'Bankia: rescue-style merger (all-share, not cash); FROB state exit; friendly cover for distressed franchise.',
    success: 'Moderate', successScore: 3,
    successNote: 'Scale logic sound; #1 domestic bank. Integration ongoing; badwill possible; too early for a clean win verdict.',
  },
  {
    deal: 'Amazon · Whole Foods', year: '2017', yearSort: 2017, value: '$13.7bn', valueSort: 13.7,
    type: 'Friendly', pay: 'All-cash', premium: '~27%', premiumSort: 27,
    motive: 'Scope (omnichannel)', outcome: 'Prime/WFM integration; sector omnichannel rush',
    successAcquirer: 'Moderate', successAcquirerScore: 3,
    successAcquirerNote: 'Strategic footprint win; catalysed omnichannel race. Financial ROI unclear (WFM under 4% of Amazon revenue).',
    successAcquiree: 'Moderate', successAcquireeScore: 3,
    successAcquireeNote: 'WFM SH: ~27% cash premium and activist exit, but lost independence and Amazon integration followed.',
    success: 'Moderate', successScore: 3,
    successNote: 'Strategic footprint win; catalysed omnichannel race. Financial ROI unclear (WFM under 4% of Amazon revenue).',
  },
  {
    deal: 'Facebook · Instagram', year: '2012', yearSort: 2012, value: '~$1bn', valueSort: 1.0,
    type: 'Bilateral', pay: 'Cash + stock', premium: 'N/A', premiumSort: null,
    motive: 'Scope (mobile)', outcome: '$32bn+ ad revenue; 3bn MAU by 2020s',
    successAcquirer: 'Exceptional', successAcquirerScore: 5,
    successAcquirerNote: 'Among the best M&A investments ever for Meta: pre-revenue bet, deferred integration, massive ad revenue creation.',
    successAcquiree: 'Exceptional', successAcquireeScore: 5,
    successAcquireeNote: 'Instagram founders/SH: $1bn+ exit pre-revenue; brand kept; founders stayed years with retention packages.',
    success: 'Exceptional', successScore: 5,
    successNote: 'Among the best M&A investments ever for Meta: pre-revenue bet, deferred integration, massive ad revenue creation.',
  },
  {
    deal: 'Kraft · Cadbury', year: '2010', yearSort: 2010, value: '$19.5bn', valueSort: 19.5,
    type: 'Hostile→friendly', pay: 'Cash + stock', premium: '~50%', premiumSort: 50,
    motive: 'Scale + India EM', outcome: 'Mondelez spin 2012; Somerdale backlash',
    successAcquirer: 'Mixed', successAcquirerScore: 2,
    successAcquirerNote: 'Kraft SH lost; hubris and overpayment. Hard synergies beat plan but Mondelez spin admitted portfolio mismatch.',
    successAcquiree: 'Strong', successAcquireeScore: 4,
    successAcquireeNote: 'Cadbury SH gained ~50% premium in hostile-to-friendly process; India prize captured by buyer but target SH won on price.',
    success: 'Mixed', successScore: 2,
    successNote: 'Kraft SH lost; hubris and overpayment. Hard synergies beat plan but Mondelez spin admitted portfolio mismatch.',
  },
  {
    deal: 'Disney · Fox', year: '2019', yearSort: 2019, value: '$71.3bn', valueSort: 71.3,
    type: 'Friendly', pay: 'Cash + stock', premium: 'Varies', premiumSort: null,
    motive: 'Scope (IP/streaming)', outcome: 'Disney+ Nov 2019; Hulu 60%; Star India',
    successAcquirer: 'Strong', successAcquirerScore: 4,
    successAcquirerNote: 'Disney+ and Hulu control validated IP/streaming thesis; high price but strategic pivot executed.',
    successAcquiree: 'Strong', successAcquireeScore: 4,
    successAcquireeNote: 'Fox assets sold near peak after Comcast counterbid; Murdoch kept Fox News/Sports in carve-out.',
    success: 'Strong', successScore: 4,
    successNote: 'Disney+ and Hulu control validated IP/streaming thesis; high price but strategic pivot executed.',
  },
  {
    deal: 'Marriott · Starwood', year: '2016', yearSort: 2016, value: '~$13.6bn', valueSort: 13.6,
    type: 'Friendly (+Anbang)', pay: 'Stock + cash', premium: 'Raised', premiumSort: null,
    motive: 'Scale + loyalty', outcome: 'Largest hotel co.; Bonvoy loyalty merged',
    successAcquirer: 'Moderate', successAcquirerScore: 3,
    successAcquirerNote: 'Scale and Bonvoy loyalty achieved; Anbang bid raised price. Integration complexity and 2018 breach temper verdict.',
    successAcquiree: 'Strong', successAcquireeScore: 4,
    successAcquireeNote: 'Starwood SH: competitive process; Anbang forced Marriott to raise; good exit for activists.',
    success: 'Moderate', successScore: 3,
    successNote: 'Scale and Bonvoy loyalty achieved; Anbang bid raised price. Integration complexity and 2018 breach temper verdict.',
  },
  {
    deal: 'VW · Porsche', year: '2009-12', yearSort: 2009, value: '€8.36bn', valueSort: 8.36,
    type: 'Reverse takeover', pay: 'Cash', premium: 'N/A', premiumSort: null,
    motive: 'Scale (forced)', outcome: 'VW absorbed Porsche AG; Porsche SE controls VW',
    successAcquirer: 'Mixed', successAcquirerScore: 2,
    successAcquirerNote: 'VW absorbed Porsche AG but saga was value-destructive (options debt, GFC rescue). Combination inevitable, process was not clean.',
    successAcquiree: 'Mixed', successAcquireeScore: 2,
    successAcquireeNote: 'Porsche AG: reverse-takeover attempt failed; options debt and forced absorption by VW; family control via Porsche SE persists.',
    success: 'Mixed', successScore: 2,
    successNote: 'VW absorbed Porsche AG but saga was value-destructive (options debt, GFC rescue). Combination inevitable, process was not clean.',
  },
  {
    deal: 'LVMH · Tiffany', year: '2021', yearSort: 2021, value: '$15.8bn', valueSort: 15.8,
    type: 'Friendly + suit', pay: 'All-cash', premium: '34.2%', premiumSort: 34.2,
    motive: 'Scope (jewellery)', outcome: 'Record Tiffany revenue 2021; W&J profit doubled',
    successAcquirer: 'Strong', successAcquirerScore: 4,
    successAcquirerNote: 'Bulgari playbook worked; record Tiffany revenue; closed gap vs Richemont despite strategic premium.',
    successAcquiree: 'Strong', successAcquireeScore: 4,
    successAcquireeNote: 'Tiffany SH: large all-cash premium (renegotiated $135 to $131.50); MAC litigation resolved with still-attractive price.',
    success: 'Strong', successScore: 4,
    successNote: 'Bulgari playbook worked; record Tiffany revenue; closed gap vs Richemont despite strategic premium.',
  },
];

const EXAM_FRAMEWORK = [
  { topic: 'Synergy equation', formula: 'Value(A+B) = Value A + Value B + Synergies · Premium must be < Synergies' },
  { topic: 'Scale vs scope', formula: 'Scale = cost synergies, market share · Scope = new capabilities, geography, IP' },
  { topic: '4 acquisition motives', formula: 'Efficiency (creates value) · Market position · Managers/hubris · Opportunity' },
  { topic: 'Control premium', formula: 'Average ~35% (US studies) · Price = Value B + Control Premium' },
  { topic: 'EBITDA multiple', formula: 'Price = (Multiple × EBITDA) − Debt' },
  { topic: 'MBO leverage', formula: 'Typical Debt/EBITDA 3–5× post-deal · Share value = (EBITDA × Exit Multiple) − Net Debt' },
  { topic: 'PE fund economics', formula: 'GP: 2% mgmt fee + 20% carry above ~8% hurdle · 10-year fund life' },
  { topic: 'IPO costs', formula: 'Direct 5–10% of proceeds · Indirect undervaluation 10–15% (first-day pop)' },
  { topic: 'Badwill', formula: 'Buy below book → negative goodwill (banks)' },
  { topic: 'MAC clause', formula: 'Material Adverse Change  -  renegotiate or litigate (Tiffany)' },
];

const LECTURE_LABELS = {
  1: 'L1  -  Introduction',
  2: 'L2  -  Acquisition Process',
  3: 'L3  -  Post-Acquisition',
  5: 'L5  -  MBOs',
  6: 'L6  -  PE & VC',
  7: 'L7  -  Takeovers',
  8: 'L8  -  IPO',
};

const STUDY_LECTURES = [
  {
    id: 1,
    title: 'Lecture 1  -  Introduction to M&A',
    overview: 'External growth exists because markets move too fast for organic growth alone. Only synergies create real economic value; market power redistributes it; managerial hubris destroys it.',
    sections: [
      { h: 'Organic vs inorganic growth', html: '<p><strong>Organic:</strong> slower, full control, homogeneous culture, funded from own cash flow.<br><strong>Inorganic:</strong> faster critical mass; access to markets, tech, people; integration and culture risk.</p>' },
      { h: 'Four motivations for acquisitions', html: '<table><tr><th>Motive</th><th>Creates value?</th></tr><tr><td><strong>1. Efficiency / synergies</strong></td><td>Yes  -  only motive that truly creates value</td></tr><tr><td><strong>2. Market position</strong></td><td>Partially  -  market power, diversification</td></tr><tr><td><strong>3. Managers</strong></td><td>No  -  agency, hubris, imitation</td></tr><tr><td><strong>4. Opportunity</strong></td><td>No  -  buy cheap without strategic vision</td></tr></table>' },
      { h: 'Synergies', html: '<p><strong>Value(A+B) = Value A + Value B + Synergies</strong><br>Price = Value B + Control Premium (~35% avg). Premium must be &lt; synergies for acquirer to gain.</p><p><strong>Soft:</strong> cross-sell, market power pricing, diversification.<br><strong>Hard:</strong> personnel, production scale, tax, commercial, financial  -  more reliable.</p>' },
      { h: 'Deal types by sector', html: '<table><tr><th>Type</th><th>Integration</th><th>Risk</th></tr><tr><td>Horizontal</td><td>High</td><td>Antitrust, culture, ~67% manager turnover in 4 yrs</td></tr><tr><td>Vertical</td><td>Medium</td><td>Admin/finance redundancies</td></tr><tr><td>Diversification</td><td>Low</td><td>Fewer synergies</td></tr></table>' },
      { h: 'Legal forms (commitment ladder)', html: '<p>Distribution → Licence → Consortium → JV → Minority stake → Majority → 100% acquisition → <strong>Merger</strong> (highest commitment; spin-off to reverse).</p>' },
    ],
    traps: ['Only synergies create value  -  hubris and pure opportunism destroy it', 'Hard synergies more reliable than soft  -  discount revenue synergies', 'Sellers rarely disclose real reasons  -  buyer must investigate', 'Horizontal = highest cultural conflict'],
  },
  {
    id: 2,
    title: 'Lecture 2  -  The Acquisition Process',
    overview: 'M&A is a 12-phase process managing information asymmetry. Due diligence is the key risk tool; earn-outs bridge price gaps; auctions create winner\'s curse risk.',
    sections: [
      { h: '12 phases', html: '<ol><li>Business objectives</li><li>Acquisition plan</li><li>Selection criteria</li><li>Search & screen</li><li>First contact</li><li>Negotiation</li><li>Structuring</li><li><strong>Integration plan</strong></li><li><strong>Due diligence</strong></li><li>Closing</li><li>Post-acquisition integration</li><li>Post-acquisition analysis</li></ol><p class="trap-inline">Integration plan (8) comes BEFORE due diligence (9)  -  DD verifies assumptions.</p>' },
      { h: 'Negotiation', html: '<p>NDA at first contact · Lock-out/exclusivity · BATNA logic · <strong>Auction → winner\'s curse</strong> (winner often overpays).</p>' },
      { h: 'Valuation & payment', html: '<p>DCF · EBITDA multiple: <strong>Price = Multiple × EBITDA − Debt</strong> · Asset-based.<br>Payment: cash (certainty) · shares (seller becomes shareholder) · <strong>earn-out</strong> (deferred, aligns incentives, metric conflict risk).</p>' },
      { h: 'Shares vs assets', html: '<p><strong>Share deal:</strong> inherits all liabilities, keeps tax credits.<br><strong>Asset deal:</strong> cherry-pick assets, avoid unknown liabilities; seller may remain competitor.</p>' },
      { h: 'Due diligence types', html: '<p>Financial · Tax · Legal · Labour · Commercial · Technical · Environmental · <strong>Cultural</strong>. Virtual data room. Vendor DD = seller commissions own report.</p>' },
      { h: 'LOI & SPA', html: '<p><strong>LOI/MOU:</strong> non-binding framework  -  what, price, payment, exclusivity, DD deadline.<br><strong>SPA:</strong> binding  -  reps & warranties, non-compete, indemnity, arbitration.</p>' },
    ],
    traps: ['Integration plan before DD  -  not the other way around', 'Winner\'s curse in auctions  -  always have walk-away price', 'Earn-out metric can be manipulated by buyer', 'Cultural DD as important as financial DD'],
  },
  {
    id: 3,
    title: 'Lecture 3  -  Post-Acquisition Integration',
    overview: 'Post-acquisition is where value is won or lost. Hard problems = pre-deal failures; soft problems (culture, communication, management) destroy well-priced deals.',
    sections: [
      { h: 'Hard problems (pre-deal)', html: '<ul><li>Unclear strategic rationale</li><li>Unresolved DD issues</li><li>One-off vs recurring synergies</li><li>Overvalued synergies</li><li>Excessive price</li><li>No integration plan</li></ul>' },
      { h: 'Soft problems (post-deal)', html: '<ul><li>Cultural collision</li><li>Management team clash</li><li>Poor communication</li></ul>' },
      { h: 'Cultural risk by deal type', html: '<p>Horizontal = <strong>high</strong> · Vertical = medium · Diversification = low.</p>' },
      { h: 'Seven emotional dimensions', html: '<p>Anger · Cultural distance · Fear · Breach of psychological contract · Feeling of loss · Loss of identity · Winners vs losers.</p>' },
      { h: 'Communication priorities', html: '<p>Employees want to know (in order): Am I included? · How do I participate? · Where is my job? · Who do I report to? · Salary/benefits?</p><p>Prompt, frequent, coherent, repeated  -  acquiring mgmt must be visible.</p>' },
      { h: 'Integration guidelines', html: '<ol><li>Define strategy + integration plan day one</li><li>Make managers visible</li><li>Appoint Integration Manager</li><li>Integrate rapidly  -  uncertainty kills retention</li><li>Prioritise actions; involve acquired employees</li></ol>' },
    ],
    traps: ['67% of acquired managers leave within 4 years', 'Slow integration prolongs fear → talent loss', 'Communication cannot be delegated to HR alone', 'Microsoft–LinkedIn vs Kraft–Cadbury = federated vs forced integration'],
  },
  {
    id: 5,
    title: 'Lecture 5  -  Management Buyouts (MBOs)',
    overview: 'MBO = financial engineering converting management opportunity into a leveraged investment vehicle. Works only when cash flow is stable enough to service debt.',
    sections: [
      { h: 'Buyout types', html: '<table><tr><th>Type</th><th>Who</th></tr><tr><td>MBO</td><td>Existing managers (lower risk)</td></tr><tr><td>MBI</td><td>Outside managers</td></tr><tr><td>BIMBO</td><td>Mix</td></tr><tr><td>IBO</td><td>PE-led, no incumbent mgmt</td></tr><tr><td>LMBO</td><td>Heavy debt</td></tr><tr><td>SBO</td><td>PE buys from PE (common exit)</td></tr></table>' },
      { h: 'Newco structure', html: '<p>1. Create Newco (mgmt equity + PE equity)<br>2. Newco acquires target<br>3. Merger by absorption → <strong>debt sits on target balance sheet</strong></p><p>Senior debt (lower rate, secured) + mezzanine/subordinated (higher rate, warrants).</p>' },
      { h: 'Ideal target', html: '<p>Stable predictable FCF · Strong brands · Low existing debt · Moderate CAPEX/WC · Management improvement opportunity · Realistic exit.</p>' },
      { h: 'Seven sources of value', html: '<p><strong>Share value = (EBITDA × Exit Multiple) − Net Debt</strong></p><ol><li>Select good target</li><li>Negotiate low entry price</li><li>Leverage acquisition</li><li>Ratchet / incentive terms</li><li>Optimise P&L (EBITDA)</li><li>Optimise balance sheet</li><li>High exit multiple</li></ol>' },
      { h: 'Exit & PE targets', html: '<p>Trade sale · MBO · SBO · IPO · Write-off.<br>PE target: <strong>IRR &gt; 15%</strong>, exit multiple ≥ 2×, horizon 3–7 years.</p><p><strong>Equity ratchet:</strong> mgmt % rises if IRR/multiple threshold hit.</p>' },
      { h: 'LBU', html: '<p>Leveraged Build-Up: buy platform + roll-up acquisitions in fragmented industries (catering, hotels, printing).</p>' },
    ],
    traps: ['Debt/EBITDA typically 3–5× post-MBO vs &lt;1× pre-deal', 'Priority post-close: service the debt', 'Managers\' "6 Fs": focused, fast, flexible, flat, frugal, friendly', 'Leverage amplifies returns AND risk'],
  },
  {
    id: 6,
    title: 'Lecture 6  -  Private Equity & Venture Capital',
    overview: 'PE/VC is the institutional infrastructure behind MBOs. The GP/LP fund model (2+20, 10-year horizon) shapes every entry and exit decision.',
    sections: [
      { h: 'Fund structure', html: '<p><strong>GP:</strong> manages fund, earns 2% p.a. + <strong>20% carry</strong> above ~8% hurdle.<br><strong>LP:</strong> pension funds, insurers, SWFs  -  commit ~10 years, passive.</p>' },
      { h: 'VC investment stages', html: '<p>Seed → Start-up → Expansion/Development → Replacement → <strong>Buyout</strong> → Turnaround.</p>' },
      { h: 'Expansion capital', html: '<p>Minority/majority stake in growing company; exit 3–7 years via capital gain + dividends.<br>Control via board seats + veto rights (CAPEX, dividends, key hires).</p>' },
      { h: 'Why take PE money', html: '<p>Growth without dangerous debt · Professionalise governance · Image & contacts · Strategic support.</p>' },
      { h: 'Governance rights', html: '<p><strong>Tag-along:</strong> minority can join majority sale on same terms.<br><strong>Drag-along:</strong> majority can force minority to sell.</p>' },
      { h: 'Business angels', html: '<p>Individuals, &lt;€1M, seed/start-up, money + experience + contacts. EBAN/ESBAN networks.</p>' },
    ],
    traps: ['Carry aligns GP with outperformance above hurdle', 'Expansion capital ≠ day-to-day ops  -  governance not management', 'Buyout is a VC stage category (mature companies)', '10-year fund life forces exit timing'],
  },
  {
    id: 7,
    title: 'Lecture 7  -  Takeovers of Listed Companies',
    overview: 'Listed takeovers operate in a regulated framework. Hostile vs friendly determines tactics; poison pills buy time; bear hug forces board dilemma; price usually decides outcome.',
    sections: [
      { h: 'Friendly vs hostile', html: '<table><tr><th></th><th>Friendly</th><th>Hostile</th></tr><tr><td>Board</td><td>Supports</td><td>Opposes</td></tr><tr><td>Consideration</td><td>Cash or stock</td><td>Usually cash</td></tr><tr><td>Bidders</td><td>Often one</td><td>Often multiple</td></tr><tr><td>Free float</td><td>Low</td><td>High (dispersed)</td></tr></table>' },
      { h: 'Spain mandatory rules', html: '<p>Voting rights &gt; <strong>30%</strong> → must bid for 100%.<br>Board seats &gt; <strong>50%</strong> → must bid for 100%.<br>Insider trading strictly prohibited.</p>' },
      { h: 'Pre-bid defenses', html: '<p>Golden parachutes · Shark repellents · <strong>Poison pills</strong> (dilute acquirer) · Crown jewels sale · Friendly share concentration · Leverage balance sheet.</p>' },
      { h: 'Post-bid defenses', html: '<p>Legal action · <strong>White Knight</strong> · Asset restructuring · <strong>Pac-Man</strong> (target bids for attacker) · White Squire.</p>' },
      { h: 'Buyer tactics vs resistant board', html: '<p>Negotiate · <strong>Bear hug</strong> (public offer board can\'t refuse without SH revolt) · Bloc with large SH · Open-market accumulation · Hostile bid to all SH.</p>' },
      { h: 'UK PUSU (Kraft–Cadbury)', html: '<p>"Put up or shut up"  -  28-day clock after public LOI; firm bid or 6-month bar. Scheme of arrangement needs 75% SH + court.</p>' },
    ],
    traps: ['Poison pills slow but rarely stop determined bidder with capital', 'Bear hug = most powerful single tool', 'White Knight saves company but at higher price', 'Hostile targets: dispersed ownership, depressed price, low debt'],
  },
  {
    id: 8,
    title: 'Lecture 8  -  IPO / Stock Market Flotation',
    overview: 'IPO converts private company to public  -  liquidity for shareholders and access to capital markets. Structural undervaluation (10–15%) is the price of making the book work.',
    sections: [
      { h: 'IPO forms', html: '<p><strong>Primary:</strong> new shares → company raises capital.<br><strong>Secondary:</strong> existing SH sell  -  no new money.<br><strong>Equity carve-out:</strong> float part of subsidiary, parent keeps control.</p>' },
      { h: 'Pros & cons', html: '<p><strong>Pros:</strong> capital access, liquidity, valuation, prestige, stock options, M&A currency.<br><strong>Cons:</strong> disclosure, 5–10% direct cost, 10–15% undervaluation, loss of control, agency costs.</p>' },
      { h: 'IPO process', html: '<p>Kick-off → DD & valuation → draft prospectus → CNMV filing → road show → book-building → price set → contracts → trading → <strong>stabilisation (greenshoe, 1 month)</strong>.</p>' },
      { h: 'Greenshoe', html: '<p>Over-allotment option up to ~15% extra shares if demand exceeds supply  -  stabilises post-IPO price.</p>' },
      { h: 'Placement types', html: '<p><strong>Firm commitment:</strong> underwriter buys entire issue (full risk).<br>Best efforts · All-or-none · Self-distribution.</p>' },
      { h: 'Spain minimum requirements', html: '<p>Capital &gt; €1,202,025 · &gt;100 shareholders · Profitability thresholds (6% of capital in 2 of last years, or 3 of 5).</p>' },
    ],
    traps: ['First-day pop = structural cost, not free money', 'Book-building sets price from institutional demand', 'IPO often PE exit route and M&A currency (Instagram IPO context)', 'Best timing = bull market'],
  },
];

/** Tabbed deal summaries (Study hub) — keyed by STUDY_DEALS id */
const DEAL_RESUMOS = {
  1: {
    label: 'MSFT / LinkedIn',
    typeLabel: 'Complementary scope',
    verdict: 'ok',
    verdictLabel: 'Strong strategic and financial success',
    struct: [
      ['Acquirer', 'Microsoft (Satya Nadella)'],
      ['Target', 'LinkedIn (Jeff Weiner)'],
      ['Value', '$26.2bn (all-cash)'],
      ['Price', '$196/share'],
      ['Premium', '49.5% over pre-announcement close'],
      ['Financing', '~$20bn bond issuance (avoid repatriation tax)'],
      ['Implied multiple', 'EV/Revenue 8.76x; EV/EBITDA 33.6x'],
      ['Termination fee', '$725m each side (symmetric)'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Microsoft opens at $160/share' },
      { dot: 'rejected', text: 'Salesforce counters at $165 (cash + stock mix)' },
      { dot: 'rejected', text: 'Salesforce raises to $171 (50% cash / 50% stock)' },
      { dot: 'rejected', text: 'Microsoft raises to $172 all-cash' },
      { dot: 'rejected', text: 'Salesforce final ~$200 (execution risk on stock component)' },
      { dot: 'accepted', text: '$196/share Microsoft all-cash — ACCEPTED (certainty beat nominal Salesforce premium)' },
      { dot: 'close', text: 'EC clearance; closes Dec 2016' },
    ],
    motivAcquirer: 'Access to the professional graph (structured career data impossible to replicate organically). Integrate Sales Navigator with Dynamics 365 to compete with Salesforce in CRM. Distribute LinkedIn Learning via Office/Teams. Defensive move against Salesforce, Google, and Facebook in enterprise data.',
    motivTarget: 'Azure migration cuts capex; Microsoft enterprise sales force for distribution. Federated autonomy: Weiner stayed CEO, brand preserved (Nokia lesson). Liquidity for shareholders at ~50% premium when standalone equity story was weak after Feb 2016 sell-off.',
    result: 'Members grew from 433M to 825M+ by 2020. Revenue quintupled toward $15bn+. Sales Navigator + Dynamics synergies; Azure migration ~$150M run-rate savings by 2018. Federated integration avoided Nokia-style failure. Shares fell ~3% on announcement but long-run scope thesis delivered.',
    traps: ['All-cash vs Salesforce stock mix — structure mattered as much as price', 'Scope deal, not cost-cutting', '$20bn bonds at ~2% vs 35% repatriation tax', 'Nokia lesson → kept LinkedIn brand and CEO autonomy'],
  },
  2: {
    label: 'CaixaBank / Bankia',
    typeLabel: 'Domestic scale merger',
    verdict: 'mix',
    verdictLabel: 'Sound scale logic; integration still underway',
    struct: [
      ['Acquirer', 'CaixaBank (listed successor to la Caixa)'],
      ['Target', 'Bankia (state-owned ~61.8% via FROB)'],
      ['Value', '~€4.3bn equity consideration'],
      ['Consideration', 'All-share (0.6845 CBK per Bankia share)'],
      ['Premium', '20% over unaffected exchange ratio'],
      ['Combined scale', '~€660bn assets; Spain #1 domestic bank'],
      ['Sector driver', 'Negative ECB rates, branch overcapacity, COVID provisions'],
      ['Accounting note', 'Badwill / negative goodwill possible when buying below book'],
    ],
    rounds: [
      { dot: 'accepted', text: 'Sep 2020: friendly merger by absorption announced' },
      { dot: 'close', text: 'ECB guide (Jan 2021): integration plans not auto-penalised' },
      { dot: 'close', text: 'Mar 2021: deal closes — FROB state exit complete' },
    ],
    motivAcquirer: 'Scale first (defend ROE in compressed NIM environment). Cost synergies from overlapping branches, IT, and admin. Fee-income cross-sell second; regulatory power as by-product. Domestic consolidation wave: Intesa/UBI, Unicaja/Liberbank.',
    motivTarget: 'Friendly cover for distressed fundamentals. State seller (FROB) set the clock — political timing mattered. All-share structure: no cash liquidity event beyond premium embedded in ratio.',
    result: 'Created Spain\'s largest bank (~20M+ customers). Branch and platform integration ongoing. Comparable to other European in-market bank mergers. Too early for a clean acquirer win verdict; badwill strengthens capital if applicable.',
    traps: ['All-share, not cash', 'Badwill possible when buying below book', 'State seller (FROB) — political timing mattered', 'COVID accelerated consolidation logic'],
  },
  3: {
    label: 'Amazon / Whole Foods',
    typeLabel: 'Capability / physical retail entry',
    verdict: 'mix',
    verdictLabel: 'Strategic option purchase — financial ROI unclear',
    struct: [
      ['Acquirer', 'Amazon (Jeff Bezos)'],
      ['Target', 'Whole Foods (John Mackey) — JANA activist 8.8%'],
      ['Value', '$13.7bn (all-cash)'],
      ['Price', '$42/share'],
      ['Premium', '~27% over closing price'],
      ['Financing', '$16bn bond offering (AA- rating)'],
      ['EV/EBITDA', '~10.4–10.6x (vs US retail take-out median ~9.9x)'],
      ['Strategic framing', 'WFM <4% of Amazon revenue — option value, not earnings'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Apr 2017: JANA reveals 8.8% stake — stock rises 10%' },
      { dot: 'rejected', text: 'WFM runs strategic review — 7 bidders (Amazon + strategics + PE)' },
      { dot: 'rejected', text: 'May 23: Amazon proposes $41/share with exclusivity — WFM counters $45' },
      { dot: 'accepted', text: 'Jun 1: Amazon "best and final" $42 with ultimatum — board approves same day' },
      { dot: 'close', text: 'Aug 28 2017: closes; FTC approved without second request' },
    ],
    motivAcquirer: 'Three capability gaps: (1) premium urban physical stores, (2) perishables and fresh supply chain, (3) trusted organic brand. Bezos had said a $200bn company must sell food. Block competitors from WFM real estate.',
    motivTarget: 'Activist JANA forced sale process. Mackey wanted brand and mission preserved. Scale vs Kroger/Costco organic push. Technology partner narrative for digital transformation.',
    result: 'Immediate goals met: stores, fresh supply chain, Prime discounts, lockers, delivery integration. Eight years on, Amazon still <3% US grocery vs Walmart ~19%. Sector-wide omnichannel rush triggered. Cultural friction (OTS system); Mackey left 2022. Best framed as learning lab, not clear financial home run.',
    traps: ['Scope deal — revenue synergies speculative', 'WFM <4% of Amazon sales — option value framing', 'Activist (JANA) forced process', 'Triggered competitor omnichannel M&A wave'],
  },
  4: {
    label: 'Meta / Instagram',
    typeLabel: 'Defensive mobile acquisition',
    verdict: 'ok',
    verdictLabel: 'Exceptional success',
    struct: [
      ['Acquirer', 'Facebook / Meta (Mark Zuckerberg)'],
      ['Target', 'Instagram (Systrom & Krieger) — 13 employees'],
      ['Nominal value', '$1bn (announcement)'],
      ['Value at close', '~$715m (FB shares fell post-IPO)'],
      ['Consideration', '$300m cash + 23M FB shares'],
      ['Premium', 'N/A — pre-revenue (Series B at $500M weeks before)'],
      ['Users at deal', '30M+ iOS; zero revenue'],
      ['Retention', '~$194M unvested packages over 3 years'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Twitter offers ~$525M to Systrom — competitive trigger' },
      { dot: 'rejected', text: 'Systrom opens negotiation at $2bn' },
      { dot: 'accepted', text: 'Zuckerberg offers $1bn — ACCEPTED over a weekend at his home' },
      { dot: 'close', text: 'FTC approves 5-0 without conditions — Aug 2012 (later antitrust suit 2020)' },
    ],
    motivAcquirer: 'Close critical mobile gap before $16bn IPO (5 weeks later). Neutralise credible mobile rival. Instant mobile-native product team. Young demographic and engagement data for ad targeting. Competitive pre-emption vs Twitter.',
    motivTarget: 'Facebook infrastructure to scale without operational overload. Immediate liquidity for founders and investors. Brand preserved as separate product (deferred integration). Protection from less friendly acquirer.',
    result: '30M → 3bn+ MAU. ~40% of Meta revenue from Instagram by mid-2020s. $32bn+ annual ad revenue by 2024. Among the best M&A investments ever. Founders stayed 6 years then left 2018 — governance cost, not financial failure. Regulatory shadow: FTC suit 2020, Meta prevailed 2025.',
    traps: ['Pre-revenue valuation — strategic optionality', 'Deferred integration preserved brand', 'Announced $1bn vs ~$715m at close (share price moved)', '5 weeks before IPO — timing not coincidental'],
  },
  5: {
    label: 'Kraft / Cadbury',
    typeLabel: 'Scale + emerging markets',
    verdict: 'mix',
    verdictLabel: 'Strategic direction right; acquirer shareholders lost',
    struct: [
      ['Acquirer', 'Kraft (Irene Rosenfeld; activist Nelson Peltz)'],
      ['Target', 'Cadbury (pure-play post-2008 demerger)'],
      ['Value', '$19.5bn / £11.9bn'],
      ['Consideration', 'Cash + Kraft shares'],
      ['Premium', '~50%'],
      ['Promised synergies', '$675m (hard faster than revenue)'],
      ['Key prize', 'India: 70%+ share in some confectionery segments'],
      ['Sector trigger', 'Mars–Wrigley $23bn (2008) left Cadbury as only large independent'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Sep 2009: initial approach rejected' },
      { dot: 'rejected', text: 'Nov 2009: hostile £9.8bn bid' },
      { dot: 'accepted', text: 'Jan 2010: raised to £11.9bn ($19.5bn) — board accepts (hostile → friendly)' },
      { dot: 'close', text: 'Feb 2010: closes under UK Takeover Panel scrutiny' },
    ],
    motivAcquirer: 'Global snacks scale after Mars–Wrigley closed the set. India distribution — the real strategic prize. Weak US/Western Europe exposure; underexposed to EM. Activist Peltz pressure for transformative M&A. Hubris / agency risk.',
    motivTarget: 'Last large independent global confectioner — structurally inevitable target. ~50% premium in hostile-to-friendly process. UK heritage and brand value. Quaker roots / Bournville identity.',
    result: 'Hard synergies beat plan; revenue synergies missed. Somerdale controversy: Kraft reversed promise to keep Bristol plant — shifted UK takeover politics. Mondelez spin 2012 = admission of portfolio mismatch. Cadbury SH gained ~50%; Kraft SH short-term negative. Classic hubris / overpayment case.',
    traps: ['Hostile → friendly — UK takeover rules and Somerdale', 'Hard synergies delivered, soft/revenue did not', 'Mondelez spin = portfolio mismatch admission', 'India distribution was the real prize', 'Hubris — Kraft SH did not win'],
  },
  6: {
    label: 'Disney / Fox',
    typeLabel: 'IP library + streaming scale',
    verdict: 'ok',
    verdictLabel: 'Strong strategic success',
    struct: [
      ['Acquirer', 'Disney (Bob Iger)'],
      ['Target', '21st Century Fox assets (Rupert Murdoch)'],
      ['Value', '$71.3bn (final after bidding war)'],
      ['Consideration', 'Cash + stock election ($38 cash or 0.4517 DIS)'],
      ['Excluded', 'Fox News, Fox Broadcasting → new Fox Corp'],
      ['Acquired', 'Studios, FX, Nat Geo, Star India, Hulu control'],
      ['Sector driver', 'Netflix disruption; $200bn+ content arms race 2017–19'],
      ['Cash election', '51% chose cash (oversubscribed)'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Dec 2017: Disney $52.4bn all-stock opening offer' },
      { dot: 'rejected', text: 'May 2018: Comcast $65bn all-cash counterbid' },
      { dot: 'accepted', text: 'Jun 2018: Disney $71.3bn cash+stock — Comcast withdraws' },
      { dot: 'close', text: 'Jul 2018: shareholders approve; closes Mar 2019' },
    ],
    motivAcquirer: 'Disney+ content library; Hulu 30%→60%; Star India 700M+ viewers; X-Men back to Marvel. Scale economics spread content spend. IP scarcity thesis — libraries as strategic assets vs Netflix/Amazon budgets.',
    motivTarget: 'Sell at peak valuation; cannot match streaming content budgets alone. James vs Rupert Murdoch disagreement. Murdoch kept news/sports (not streamable) in carve-out.',
    result: 'Disney+ launched Nov 2019. Hulu majority control. Integration of 21CF into DTC strategy. High price but strategic pivot executed. Comcast counterbid forced cash component and raised final price.',
    traps: ['Murdoch kept Fox News/Sports — carve-out not full sale', 'Comcast counterbid forced cash component', 'Cash election oversubscribed — financing risk', 'IP scarcity thesis — content libraries as strategic assets'],
  },
  7: {
    label: 'Marriott / Starwood',
    typeLabel: 'Scale + loyalty platform',
    verdict: 'mix',
    verdictLabel: 'Scale achieved; integration complexity',
    struct: [
      ['Acquirer', 'Marriott International'],
      ['Target', 'Starwood (SPG loyalty; 1,297 properties)'],
      ['Value', '~$13.6bn'],
      ['Consideration', '0.80 MAR shares + $21 cash per HOT share'],
      ['Combined', '5,700 properties; 1.1M rooms — largest hotel merger ever'],
      ['Loyalty', '~75M combined members (54M MR + 21M SPG)'],
      ['Cost synergies', '$200M→$250M/yr (reservations, purchasing, HQ)'],
      ['Competitive bid', 'Anbang consortium counterbid Mar 2016'],
    ],
    rounds: [
      { dot: 'accepted', text: 'Nov 2015: friendly deal signed' },
      { dot: 'rejected', text: 'Mar 2016: Anbang consortium counterbid — Marriott must raise' },
      { dot: 'accepted', text: 'Raised to 0.80 shares + $21 cash — shareholders approve Apr 2016' },
      { dot: 'close', text: 'Sep 2016: closes; SPG merged into Marriott Bonvoy (2018)' },
    ],
    motivAcquirer: 'Scale #1 globally; bargaining power vs OTAs (15–25% commissions). SPG loyalty was core asset. Starwood stronger internationally and in luxury (W, St. Regis, Westin). Asset-light synergies in G&A/systems.',
    motivTarget: 'Strategic review (Lazard, Apr 2015). Declining revenue ($6.1bn→$5.8bn). Activist pressure. Competitive process forced Marriott to raise price via Anbang bid.',
    result: 'Largest hotel company; Bonvoy loyalty platform vs Airbnb and OTAs. Integration complexity across 30 brands. 2018 data breach tempered verdict. Anbang later bought Strategic Hotels $6.5bn — Chinese capital in hospitality 2015–16.',
    traps: ['Anbang counterbid — Chinese capital in hospitality', 'SPG was core asset — loyalty moat', 'Starwood seller weakness (declining revenue, activists)', 'Asset-light — synergies in G&A/systems not property'],
  },
  8: {
    label: 'VW / Porsche',
    typeLabel: 'Contested control / reverse takeover',
    verdict: 'mix',
    verdictLabel: 'Combination inevitable; process was messy',
    struct: [
      ['Acquirer (final)', 'Volkswagen AG'],
      ['Operating target', 'Porsche AG'],
      ['Total paid by VW', '~€8.36bn (49.9% in 2009 + 50.1% in 2012)'],
      ['Control vehicle', 'Porsche SE still holds ~50.7% VW voting rights'],
      ['Deal type', 'Reverse takeover — Porsche tried to buy VW first'],
      ['Options debt', '€14bn cash-settled options at GFC peak'],
      ['Porsche RoE vs VW', '~22.8% vs ~3.0% (2005) — asymmetry drove strategy'],
      ['IPO 2022', 'Porsche AG ~€75bn valuation'],
    ],
    rounds: [
      { dot: 'rejected', text: '2005–2008: Porsche SE builds VW stake via cash-settled options to 74.1%' },
      { dot: 'rejected', text: 'Oct 2008: short squeeze — VW briefly world\'s most valuable company' },
      { dot: 'rejected', text: '2009: GFC freezes credit; Porsche net income −83% H1 2009' },
      { dot: 'accepted', text: 'Mar 2009: VW lends Porsche €700m — power flips' },
      { dot: 'accepted', text: 'VW acquires 49.9% Porsche AG for €3.9bn (2009)' },
      { dot: 'close', text: 'Aug 2012: VW absorbs remaining Porsche AG operating business' },
    ],
    motivAcquirer: '(VW) Absorb Porsche AG — highest margin brand per unit; platform sharing (Touareg/Q7/Cayenne); R&D scale. Resist Porsche SE hostile control attempt.',
    motivTarget: '(Porsche SE) Originally: control VW to protect family. Reality: financial survival after leveraged options strategy failed. Family Porsche-Piëch retains influence via holding structure.',
    result: 'Combination delivered platform synergies and 2022 IPO at ~9x cash cost. Saga was value-destructive in process (options debt, rescue loan). Porsche SE emerged diminished — from aspiring acquirer to dividend-dependent holding. Oct 2008 short squeeze is a famous market event.',
    traps: ['Reverse takeover — not a normal friendly merger', 'Cash-settled options created hidden leverage', 'Family control persists via Porsche SE', 'Porsche RoE vs VW RoE explains bidding aggression'],
  },
  9: {
    label: 'LVMH / Tiffany',
    typeLabel: 'Luxury brand acquisition',
    verdict: 'ok',
    verdictLabel: 'Strong strategic success in progress',
    struct: [
      ['Acquirer', 'LVMH (Bernard Arnault)'],
      ['Target', 'Tiffany & Co. (NYSE-listed)'],
      ['Final value', '~$15.8bn'],
      ['Original deal', '$135/share — Nov 2019'],
      ['Renegotiated', '$131.50/share — Oct 2020 (MAC litigation)'],
      ['Premium', '34.2% over undisturbed ($98)'],
      ['Financing', '€10bn bonds + €5bn cash'],
      ['EV/EBITDA', '~19x vs peer median ~12x'],
    ],
    rounds: [
      { dot: 'rejected', text: 'Oct 2019: LVMH $120/share — unsolicited, Tiffany not for sale' },
      { dot: 'accepted', text: 'Nov 2019: $135/share — board approves (+37%)' },
      { dot: 'rejected', text: 'Sep 2020: LVMH invokes MAC (Covid) — tries to withdraw' },
      { dot: 'rejected', text: 'Tiffany sues in Delaware Chancery to force close' },
      { dot: 'accepted', text: 'Oct 2020: revised $131.50 (-$3.50) — litigation settled' },
      { dot: 'close', text: 'Jan 2021: closes' },
    ],
    motivAcquirer: 'Close gap vs Richemont (Cartier, Van Cleef). US bridal dominance; hard luxury scarcity. Watches & Jewellery only 8% of group vs 44% Fashion. Bulgari 2011 as integration template.',
    motivTarget: 'Fund "Next Generation" transformation; Asia expansion via LVMH network. Large all-cash premium vs standalone execution risk. Millennial relevance slipping pre-deal.',
    result: 'Record Tiffany revenue 2021. Watches & Jewellery operating profit doubled. High jewellery sales quadrupled toward 2025. MAC clause litigation resolved with still-attractive price. Leadership fully replaced at close — LVMH playbook applied.',
    traps: ['MAC clause / pandemic litigation — renegotiation not walk-away', 'All-cash despite bond financing', 'Trophy asset — strategic premium over DCF', 'Bulgari 2011 as integration template', '$120 → $135 → $131.50 price path'],
  },
};

const DEAL_RESUMO_ORDER = [1, 2, 3, 4, 5, 6, 7, 8, 9];
